<%-- 
    Document   : termsofuse
    Created on : Apr 25, 2016, 2:37:37 PM
    Author     : sathuluri
--%>

<%@taglib prefix="c" uri="/WEB-INF/tlds/c.tld" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=9; IE=10; IE=EDGE" />
        <meta name="viewport" content="width=device-width" />
        <title>IRMaaS</title>
        <!-- CSS : Include -->
        <link rel="stylesheet" href="<c:url value="/css/general2.css"/>" />
        <!-- CSS : Include -->
    </head>
    <body>
        <!-- Start: Wrapper -->
        <div class="ux-head">
                <div class="ux-head-cntr-logo">
                    <span class="ux-head-logo">
                        <img src="<c:url value="/images/OPTUM-LOGO-Security-Solutions_no-padding.png"/>" alt="Product Name" />
                    </span>
                </div>
            </div>
        <div class="ux-content ux-margin-3t">

            <div class="ux-panl ux-terms-content">
                <div class="ux-panl-header ux-panl-with-underline">
                    <h2>Terms of Use</h2>
                </div>
                <div class=" ux-panl-content">
                    <h3  class="ux-margin-bottom-halft">IMPORTANT NOTE REGARDING WEBSITE CONTENT</h3>
                    <p>This website is intended for a United States audience. If you live outside the U.S., you may see information on this website about products or therapies that are not available or authorized in your country.</p>
                    <h3 class="ux-margin-bottom-halft">Agreement and Terms</h3>
                    <p>These website Terms of Use  (&quot;Terms&quot;) describe the rules for using this website. These Terms  constitute a legally binding agreement between you, the person using this  website, and Optum. Terms such as &quot;we&quot; or &quot;our&quot; and  &quot;Company&quot; refer to Optum and its affiliate entities.</p>
                    <p> By using this website, you agree to the most-recent Terms  as well as the most-recent version of our&nbsp;<a href="https://10.5.0.23/IRM/PrivacyPolicy.htm">Privacy Policies</a>. We may change these Terms at any time, and such changes will  be posted on this or a similar page of this website. It is your responsibility  to review these Terms each time you use this website. By continuing to use this  website, you consent to any changes to our Terms.</p>
                    <p> By using this website, you  acknowledge and agree that any activity on this website is subject to  monitoring by the Company at any time, and that the Company may use the results  of such monitoring without limitation, subject to applicable law.</p>
                    <p>By logging into Optum Security Solutions<strong> </strong>you are acknowledging  that you are an authorized user; that unauthorized or improper use of Optum Security Solutions may result in disciplinary action, as well as civil and  criminal penalties; that Optum Security Solutions<strong> </strong> usage may be monitored, recorded, and subject  to audit; that use of Optum Security Solutions indicates consent to monitoring  and recording. The use of Optum Security Solutions by individual(s) or entity  may allow access to information that is privileged, confidential and exempt  from disclosure under applicable law, including the Health Insurance  Portability and Accountability Act (PL 104-191).</p>
                    <h3 class="ux-margin-bottom-halft">License to use this website and content ownership</h3>
                    <p>Subject to these Terms, the Company  grants you a personal, nontransferable, nonexclusive, revocable, limited  license to view the Content on the website for the sole purpose of managing  your company&rsquo;s compliance-related activities. You may also print a reasonable  number of copies of the Content, but in such case you must reproduce all  proprietary copyright and trademark notices. All rights, title, and interest in  and to the website, including the Content, and all intellectual property  rights, including all copyright, trademark, patent, and trade secret rights  therein shall remain with the Company and our licensors and vendors, and no  ownership interest is transferred to you or any other entity by virtue of  making the Content available on the website, granting the foregoing licenses or  entering into this agreement.</p>
                    <p> In the event you choose to provide us  with any feedback, suggestions, or similar communications, all such messages  (collectively, &ldquo;Feedback Messages&rdquo;) will be considered non-personal,  non-confidential (except for personal information as described in our Privacy  Policies) and nonproprietary. You hereby grant the Company a perpetual, sub licensable,  assignable, unrestricted, worldwide, royalty-free, irrevocable license to use,  reproduce, display, perform, practice, modify, create derivative or collective  works, transmit and distribute your Feedback Messages, in whole or in part, and  including all intellectual property rights therein.</p>
                    <p>                      Some websites operated by the Company  include trademarks or logos belonging to other third-party licensors and are  used pursuant to an agreement with such third parties.</p>
                    <p> We may terminate this license at any  time for any reason. If you breach any of these Terms, your license to the  Content terminates immediately. Upon the termination of this license you must  stop using this website, including all Content, and return or destroy all  copies, including electronic copies, of the Content in your possession or  control.</p>
                    <p>We may use and disclose your activity information unless restricted by this policy or by law. Some examples of the ways we use your activity information include: </p>
                    <h3 class="ux-margin-bottom-halft">Restrictions on use of this website </h3>
                    <p>You agree:</p>
                    <ul class="ux-list-content-ul" >
                        <li>not to use this website or Content in any way not explicitly       permitted by these Terms or the text of the website itself;</li>
                        <li>not to copy, modify or create derivative works involving the       Content, except you may print a reasonable number of copies, provided that       you reproduce all proprietary copyright and trademark notices;</li>
                        <li>not to misrepresent your identity or provide us with any false       information in any information-collection portion of this website, such as       a registration or application page;</li>
                        <li>not to take any action intended to interfere with the operation of       this website;</li>
                        <li>not to access or attempt to access any portion of this website to       which you have not been explicitly granted access;</li>
                        <li>not to share any password assigned to or created by you with any       third parties or use any password granted to or created by a third party;</li>
                        <li>not to directly or indirectly authorize anyone else to take actions       prohibited in this section; and</li>
                        <li>to comply with all applicable laws and regulations while using this       website or the Content. You represent and warrant that you are at least 13       years of age, and that if you are between 13 and 18 years of age a parent       and/or guardian agrees to these Terms of Use on your behalf.</li>
                    </ul>
                    <div class="ux-clear"></div>
                    <h3 class="ux-margin-bottom-halft">Messages, comments or content</h3>
                    <p>We may, but are not obligated to,  restrict or remove any and all content from a message that we determine in our  sole discretion violates these Terms or is otherwise harmful to us, our customers,  or any third party. We reserve the right to remove the content you provide at  any time, but you understand that we may preserve and access a backup-copy, and  we may disclose the content if required to do so by law or in a good faith  belief that such access, preservation, or disclosure is required by law or in  the best interests of the Company.</p>
                    <p> Any content you submit is for  non-commercial use only. Any content you submit will be routed through the  Internet and you understand and acknowledge that you have no expectation of  privacy with regard to any content you submit. Never assume that you are  anonymous and cannot be identified by your posts.</p>
                    <p> If you do submit material, and unless  we indicate otherwise, you grant the Company a nonexclusive, royalty-free,  perpetual, irrevocable, and fully sub licensable right to use, reproduce,  modify, adapt, publish, translate, create derivative works from, distribute,  and display such content throughout the world in any media. You grant the  Company and any of its sub licensees the right to use the name that you submit  in connection with such content, if they choose. You represent and warrant that  you own or otherwise control all of the rights to the content that you post;  that the content is accurate; that use of the content you supply does not  violate these Terms and Conditions and will not cause injury to any person or  entity; and that you will indemnify the Company or its affiliates for all  claims resulting from content you supply.</p>
                    <h3 class="ux-margin-bottom-halft">Copyright Infringement - DMCA Notice</h3>
                    <p>The Digital Millennium Copyright Act of 1998 (the  &quot;DMCA&quot;) provides recourse for copyright owners who believe that  material appearing on the Internet infringes their rights under US copyright  law. If you believe in good faith that content or material on this website  infringes a copyright owned by you, you (or your agent) may send the Company a  notice requesting that the material be removed, or access to it blocked. This  request should be sent to:<a href="mailto:DMCARegisteredAgent2@optum.com">DMCARegisteredAgent2@optum.com</a>; or, alternatively to: UnitedHealth Group, Attn: DMCA  Registered Agent, 9900 Bren Road East, Minnetonka, MN 55343.</p>
                    <p> The notice must include the following  information: (a) a physical or electronic signature of a person authorized to  act on behalf of the owner of an exclusive right that is allegedly infringed;  (b) identification of the copyrighted work claimed to have been infringed; (c)  identification of the material that is claimed to be infringing or the subject  of infringing activity; (d) the name, address, telephone number, and email  address of the complaining party; (e) a statement that the complaining party  has a good faith belief that use of the material in the manner complained of is  not authorized by the copyright owner, its agent or the law; and (f) a  statement that the information in the notification is accurate and, under  penalty of perjury, that the complaining party is authorized to act on behalf  of the owner of an exclusive right that is allegedly infringed If you believe  in good faith that a notice of copyright infringement has been wrongly filed  against you, the DMCA permits you to send us a counter-notice. Notices and  counter-notices must meet the then-current statutory requirements imposed by  the DMCA. Notices and counter-notices with respect to the website should be  sent to the address above.</p>
                    <h3 class="ux-margin-bottom-halft">Changes to website content</h3>
                    <p>We may change, add or remove some or  all of the Content on this website at any time. In addition, please note that  although our goal is to provide accurate information, certain features that may  be offered through this website, or other Content, may not be accurate or up to  date. In addition, please note that features of the products and services  described in this website may change over time as permitted by law.</p>
                    <h3 class="ux-margin-bottom-halft">Links</h3>
                    <p>While visiting this website you may  click on a link to other websites and leave this website. We provide links to  other websites that may contain information that may be useful or interesting  to you. We do not endorse, and are not responsible for, the content and  accuracy of linked websites operated by third parties or for any of your  dealings with such third parties. You are solely responsible for your dealings  with such third parties and we encourage you to read the terms of use and  privacy policies on such third-party websites.</p>
                    <h3 class="ux-margin-bottom-halft">NO WARRANTIES</h3>
                    <p>ALL CONTENT ON THIS WEBSITE IS  PROVIDED TO YOU ON AN &quot;AS IS&quot;, &quot;AS AVAILABLE&quot; BASIS. THE  COMPANY, ALL THIRD PARTIES, IF ANY, PROVIDING CONTENT FOR THIS WEBSITE, AND ALL  THIRD PARTIES PROVIDING SUPPORT OR INFORMATION FOR THIS WEBSITE (COLLECTIVELY,  &quot;WEBSITE-RELATED-PARTIES&quot;) HEREBY DISCLAIM ALL WARRANTIES OF ANY  KIND, EITHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE INCLUDING BUT NOT  LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR  PURPOSE AND NON-INFRINGEMENT.</p>
                    <p> THE WEBSITE-RELATED-PARTIES MAKE NO  WARRANTY AS TO THE ACCURACY, COMPLETENESS, TIMELINESS, CORRECTNESS, OR  RELIABILITY OF ANY CONTENT AVAILABLE THROUGH THIS WEBSITE. WITHOUT LIMITING THE  FOREGOING, THE WEBSITE-RELATED-PARTIES SPECIFICALLY DO NOT REPRESENT OR WARRANT  THAT ANY INFORMATION PROVIDED IS ACCURATE OR COMPLETE. THE  WEBSITE-RELATED-PARTIES MAKE NO REPRESENTATIONS OR WARRANTIES THAT USE OF THIS  WEBSITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR  THAT THIS WEBSITE OR THE TECHNOLOGY THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES  OR OTHER HARMFUL COMPONENTS. YOU ARE RESPONSIBLE FOR TAKING ALL PRECAUTIONS  NECESSARY TO ENSURE THAT ANY CONTENT YOU MAY OBTAIN FROM THIS WEBSITE IS FREE OF  VIRUSES AND ANY OTHER POTENTIALLY DESTRUCTIVE COMPUTER CODE.</p>
                    <p> Some states do not allow limitations  on implied warranties, so one or more of the above limitations may not apply to  you. Check your local laws for any restrictions or limitations regarding the exclusion  of implied warranties.</p>
                    <h3 class="ux-margin-bottom-halft">LIMITATION OF LIABILITY</h3>
                    <p>YOU AGREE THAT NONE OF THE  WEBSITE-RELATED-PARTIES SHALL BE LIABLE FOR ANY DAMAGE RESULTING FROM YOUR USE  OR INABILITY TO USE THIS WEBSITE OR THE CONTENT. THIS PROTECTION COVERS CLAIMS  BASED ON WARRANTY, CONTRACT, TORT, STRICT LIABILITY, AND ANY OTHER LEGAL  THEORY. THIS PROTECTION COVERS THE WEBSITE-RELATED-PARTIES, INCLUDING ALL  AFFILIATES, AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS. THIS  PROTECTION COVERS ALL LOSSES INCLUDING, WITHOUT LIMITATION, DIRECT OR INDIRECT,  SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, AND PUNITIVE DAMAGES, PERSONAL  INJURY/WRONGFUL DEATH, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR  BUSINESS INTERRUPTION. THE TOTAL, CUMULATIVE, LIABILITY OF THE WEBSITE-RELATED-PARTIES,  INCLUDING ALL AFFILIATES, AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS,  IF ANY, FOR LOSSES OR DAMAGES SHALL BE LIMITED TO THE AMOUNT OF YOUR ACTUAL  DAMAGES, NOT TO EXCEED U.S. $100.00. THE LIMIT OF LIABILITY MAY NOT BE EFFECTIVE  IN SOME STATES. IN NO EVENT SHALL THE WEBSITE-RELATED-PARTIES, INCLUDING ALL  AFFILIATES, AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS, BE LIABLE TO  YOU FOR ANY LOSSES OR DAMAGES OTHER THAN THE AMOUNT DESCRIBED ABOVE. ALL OTHER  DAMAGES, DIRECT OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR  PUNITIVE, RESULTING FROM ANY USE OF THE WEBSITE OR CONTENT ARE EXCLUDED EVEN IF  THE WEBSITE-RELATED-PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH  DAMAGES. YOU AGREE THAT YOU USE THIS WEBSITE AT YOUR OWN RISK. IF YOU ARE  DISSATISFIED WITH THIS WEBSITE OR THE CONTENT, YOUR SOLE AND EXCLUSIVE REMEDY  IS TO DISCONTINUE USING THE WEBSITE.</p>
                    <h3 class="ux-margin-bottom-halft">Governing law and statute of limitations</h3>
                    <p>The laws of the State of Minnesota  govern these Terms and any cause of action arising under or relating to your  use of the website, without reference to its choice-of-law principles. You  agree that the only proper jurisdiction and venue for any dispute with the  Company, or in any way relating to your use of this website, is in the state  and federal courts in the State of Minnesota, U.S.A. You further agree and  consent to the exercise of personal jurisdiction in these courts in connection  with any dispute involving the Company or its employees, officers, directors,  agents, and providers. If any provision of these Terms is determined to be  invalid under any applicable statute or rule of law, such provision is to that  extent to be deemed omitted, and the balance of the agreement shall remain  enforceable.</p>
                    <p> Before seeking legal recourse for any  harm you believe you have suffered arising from or related to your use of this  website, you agree to inform us in writing and to give us 30 days to cure the  harm before initiating any action. You must initiate any cause of action within  one year after the claim has arisen, or you will be barred from pursuing any  cause of action.</p>
                    <h3 class="ux-margin-bottom-halft">Contact us</h3>
                    <p>To contact us regarding these Terms or the operation of the website itself, contact us at <a href="mailto:support@optum.com">support@optum.com</a></p>
                    <h3 class="ux-margin-bottom-halft">Effective date</h3>
                    <p>The Effective Date of these Terms is 20th Oct 2014.</p>
                    <h3 class="ux-margin-bottom-halft">Additional terms</h3>
                    <p>Your obligations under the following sections survive termination of this agreement: Important Note Regarding Website Content; Agreement and Terms; portions of License to use this website and content ownership; Restrictions on use of this website; Posting messages, comments or content; Copyright Infringement - DMCA Notice; Changes to website content; Links; NO WARRANTIES; LIMITATION OF LIABILITY; Governing law and statute of limitations; Additional terms. If any provision of these Terms is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms, which shall remain in full force and effect. No waiver of any of these Terms shall be deemed a further or continuing waiver of such term or condition or any other term or condition. You agree to defend and indemnify, Website-Related-Parties and their subsidiaries, affiliates, officers, directors, employees, and agents, harmless from any claim, demand, or damage, including reasonable attorneys' fees, arising out of or related to your breach of this agreement or your use or misuse of the Content or website. You may not transfer or assign any rights or obligations under this agreement. The Company may transfer or assign its rights and obligations under this agreement.</p>
                </div>
            </div>
        </div>
        <!-- End: Wrapper -->
    </body>
</html>