SET IDENTITY_INSERT [dbo].[PERMSN_GRP] ON 

INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (1, 1, N'Security Admin - Manage Organization and User', N'Allows the user to manage the Organizations and Users. (i.e. Add, Edit, and View). Also, allows the user to manage the User Activation. (i.e. Unlock the locked accounts and Activate the Inactive accounts)', NULL, CAST(0x0000A6BB00B690F5 AS DateTime), 3, NULL, NULL)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (2, 1, N'Manage Roles & Permissions', N'Allows the user to manage the Roles and Permissions. (i.e. Add, Edit, and View Roles)', NULL, CAST(0x0000A6BB010635CF AS DateTime), 3, NULL, NULL)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (3, 1, N'Client Engagement - Manage Engagements', N'Allows users to Manage Engagements. (i.e. Create, Update, View, and Delete)', NULL, CAST(0x0000A6BE00F5CE96 AS DateTime), 3, NULL, NULL)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (4, 1, N'Client Engagement - Manage Engagement User', N'Allows the users to Manage users to the services (i.e. Add, Update, and View)', NULL, CAST(0x0000A6BE00F622FA AS DateTime), 3, NULL, NULL)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (5, 1, N'Engagement Data Upload - Upload', N'Allows the user to respond to the Services (i.e. Allows the user to Add, Update, View, and Delete the documents for the services) and  Lock the service data.', NULL, CAST(0x0000A6BE00F67299 AS DateTime), 3, NULL, NULL)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (6, 1, N'Engagement Data Upload - Unlock', N'Allows the user to Unlock the service data', NULL, CAST(0x0000A6BE00F6E910 AS DateTime), 3, NULL, NULL)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (7, 1, N'Vulnerabilities - Review', N'Allows to ''Add, Edit, Remove'' the ''Vulnerabilities'' in the engagement, and as well allows to do the ''Review Complete'' action.  Also, allows the user to ''View, and Edit'' the remediation status', NULL, CAST(0x0000A6BE00F744A1 AS DateTime), 3, CAST(0x0000A6C1011E91F6 AS DateTime), 3)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (8, 1, N'Report and Dashboards - RW', N'Allows the user to ''Add, View, Delete, and Publish'' the reports, and allows the user to View and Publish the Dashboard to client', NULL, CAST(0x0000A6BE00F7BBA1 AS DateTime), 3, CAST(0x0000A6C1011FE973 AS DateTime), 3)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (9, 1, N'Report and Dashboards - RO', N'View Reports and Dashboards', NULL, CAST(0x0000A6BE00F84C1C AS DateTime), 3, CAST(0x0000A6C101168B38 AS DateTime), 3)
INSERT [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY], [ROW_STS_KEY], [PERMSN_GRP_NM], [PERMSN_GRP_DESC], [STS_COMMT_TXT], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (10, 1, N'Report and Dashboards - Remediate', N'Report and Dashboards - Remediate', NULL, CAST(0x0000A6BE00FB4E2E AS DateTime), 3, CAST(0x0000A6C101162D55 AS DateTime), 3)
SET IDENTITY_INSERT [dbo].[PERMSN_GRP] OFF