SET IDENTITY_INSERT [dbo].[USER_APPL_ROLE] ON 

INSERT [dbo].[USER_APPL_ROLE] ([USER_APPL_ROLE_KEY], [ROW_STS_KEY], [APPL_ROLE_KEY], [USER_ID], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (1, 1, 1, 1, CAST(0x0000A6BB00B8735F AS DateTime), 1, NULL, NULL)
INSERT [dbo].[USER_APPL_ROLE] ([USER_APPL_ROLE_KEY], [ROW_STS_KEY], [APPL_ROLE_KEY], [USER_ID], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (2, 1, 2, 3, CAST(0x0000A6BB00D4AD85 AS DateTime), 1, NULL, NULL)

SET IDENTITY_INSERT [dbo].[USER_APPL_ROLE] OFF