
SET IDENTITY_INSERT [dbo].[OWASP_TOP_10] ON 


INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (1, N'A1', N'Injection', N'Injection flaws, such as SQL, OS, and LDAP injection occur when untrusted data is sent to an interpreter as part of a command or query. The attacker’s hostile data can trick the interpreter into executing unintended commands or accessing data without proper authorization.', N'Untrusted Data input allows malicious script execution in SQL, OS, or LDAP.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (2, N'A2', N'Broken Authentication and Session Management', N'Application functions related to authentication and session management are often not implemented correctly, allowing attackers to compromise passwords, keys, or session tokens, or to exploit other implementation flaws to assume other users’ identities.', N'Weak authentication allows compromise of the application and misuse of user identity.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (3, N'A3', N'Cross-Site Scripting (XSS)', N'XSS flaws occur whenever an application takes untrusted data and sends it to a web browser without proper validation or escaping. XSS allows attackers to execute scripts in the victim’s browser which can hijack user sessions, deface web sites, or redirect the user to malicious sites.', N'Unvalidated input data allows script execution in browser to hijack session or redirect to malicious sites.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (4, N'A4', N'Insecure Direct Object References', N'A direct object reference occurs when a developer exposes a reference to an internal implementation object, such as a file, directory, or database key. Without an access control check or other protection, attackers can manipulate these references to access unauthorized data.', N'Weak access controls allow attackers to manipulate internal objects.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (5, N'A5', N'Security Misconfiguration', N'od security requires having a secure configuration defined and deployed for the application, frameworks, application server, web server, database server, and platform. Secure settings should be defined, implemented, and maintained, as defaults are often insecure. Additionally, software should be kept up to date.', N'Insecure configuration of OS, App, or DB layers to include patching/default settings provide multiple-layered attack vectors.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (6, N'A6', N'Sensitive Data Exposure', N'Many web applications do not properly protect sensitive data, such as credit cards, tax IDs, and authentication credentials. Attackers may steal or modify such weakly protected data to conduct credit card fraud, identity theft, or other crimes. Sensitive data deserves extra protection such as encryption at rest or in transit, as well as special precautions when exchanged with the browser.', N'Sensitive data may be stolen while in-transit or at-rest due to lack of encryption, poor coding practices, or security misconfigurations.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (7, N'A7', N'Missing Function Level Access Control', N'Most web applications verify function level access rights before making that functionality visible in the UI. However, applications need to perform the same access control checks on the server when each function is accessed. If requests are not verified, attackers will be able to forge requests in order to access functionality without proper authorization.', N'Unverified access control to functions may result in forged requests without authorization.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (8, N'A8', N'Cross-Site Request Forgery (CSRF)', N'A CSRF attack forces a logged-on victim’s browser to send a forged HTTP request, including the victim’s session cookie and any other automatically included authentication information, to a vulnerable web application. This allows the attacker to force the victim’s browser to generate requests the vulnerable application thinks are legitimate requests from the victim.', N'This is a browser-based attack that uses the victim''s own authentication/cookies for attacks against the application.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (9, N'A9', N'Using Components with Known Vulnerabilities', N'Components, such as libraries, frameworks, and other software modules, almost always run with full privileges. If a vulnerable component is exploited, such an attack can facilitate serious data loss or server takeover. Applications using components with known vulnerabilities may undermine application defenses and enable a range of possible attacks and impacts.', N'Use of libraries or software modules with vulnerabilities result in attacks against the application,database, or OS due to escalated privileges of the component.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

INSERT [dbo].[OWASP_TOP_10] ([OWASP_TOP_10_KEY], [OWASP_CD], [OWASP_NM], [OWASP_DESC], [OWASP_SHRT_DESC], [PUBL_DT], [CURR_IND], [CREAT_DT], [CREAT_USER_ID], [UPDT_DT], [UPDT_USER_ID]) VALUES (10, N'A10', N'Unvalidated Redirects and Forwards', N'Web applications frequently redirect and forward users to other pages and websites, and use untrusted data to determine the destination pages. Without proper validation, attackers can redirect victims to phishing or malware sites, or use forwards to access unauthorized pages.', N'Use of untrusted data to control application redirects can send victims to phishing/malware sites while forwards can result in access to unauthorized pages.', CAST(N'2013-12-06' AS Date), 1, GETDATE(), 2, NULL, NULL)

SET IDENTITY_INSERT [dbo].[OWASP_TOP_10] OFF

