SELECT DISTINCT CONVERT(VARCHAR(100),IPADR)+''+CONVERT(VARCHAR(5000),VULN_DESC)+''+CONVERT(VARCHAR(1000),VULN_NM)
FROM CVVV

SELECT RMDTN_CST_EFFRT_CD,VULN_CATGY_CD,VULN_INSTC_STS_CD FROM TAC9.CLNT_VULN_INSTC


UPDATE A
SET A.RMDTN_CST_EFFRT_CD = SUBSTRING(B.RMDTN_CST_EffORT_CD,1,1),
	A.VULN_CATGY_CD		 = B.VULN_CATGY_CD,
	A.VULN_INSTC_STS_CD	 = B.[VULN_INSTC_STS CD]
FROM TAC9.CLNT_VULN_INSTC A JOIN CVVV B
ON CONVERT(VARCHAR(100),A.IPADR)+''+CONVERT(VARCHAR(5000),A.VULN_DESC)+''+CONVERT(VARCHAR(1000),A.VULN_NM) = 
CONVERT(VARCHAR(100),B.IPADR)+''+CONVERT(VARCHAR(5000),B.VULN_DESC)+''+CONVERT(VARCHAR(1000),B.VULN_NM)

SELECT  A.RMDTN_CST_EFFRT_CD,SUBSTRING(B.RMDTN_CST_EffORT_CD,1,1),A.VULN_CATGY_CD, B.VULN_CATGY_CD,A.VULN_INSTC_STS_CD,B.[VULN_INSTC_STS CD]

FROM TAC9.CLNT_VULN_INSTC A JOIN CVVV B
ON CONVERT(VARCHAR(100),A.IPADR)+''+CONVERT(VARCHAR(5000),A.VULN_DESC)+''+CONVERT(VARCHAR(1000),A.VULN_NM) = 
CONVERT(VARCHAR(100),B.IPADR)+''+CONVERT(VARCHAR(5000),B.VULN_DESC)+''+CONVERT(VARCHAR(1000),B.VULN_NM)