var dataStringPierc4 ='<chart caption="TBD" numberSuffix="%" labelDisplay="wrap" maxLabelWidthPercent="40"  captionAlignment="left"   numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="60" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="1" bgratio="0" startingangle="-160" animation="1"> <set value="45" label="Lack of patch management&#10; process/Patch validation" color="078576"/> <set value="30" label="Lack of secure code - &#10;parameter policy/Validation" color="66a36f" /> <set value="15"  label="Lack of security configuration&#10; policy/Validation" color="9cc366"  /> <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';

var dataStringPie3 ='<chart caption="Route Cause Analysis" numberSuffix="%" labelDisplay="wrap" maxLabelWidthPercent="40"  captionAlignment="left"   numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="60" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="1" bgratio="0" startingangle="-160" animation="1"> <set value="45" label="Lack of patch management&#10; process/Patch validation" color="523995"/> <set value="30" label="Lack of secure code - &#10;parameter policy/Validation" color="6a6ab3" /> <set value="15"  label="Lack of security configuration&#10; policy/Validation" color="8d99cd"  /> <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';

var dataStringPie3Hitrust ='<chart caption="HITRUST Mapping" numberSuffix="%" labelDisplay="wrap" maxLabelWidthPercent="40"  captionAlignment="left"   numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="60" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="1" bgratio="0" startingangle="-160" animation="1"> <set value="45" label="Lack of patch management&#10; process/Patch validation" color="078576"/> <set value="30" label="Lack of secure code - &#10;parameter policy/Validation" color="66a36f" /> <set value="15"  label="Lack of security configuration&#10; policy/Validation" color="9cc366"  /> <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';

var dataStringPieOWASP3 ='<chart caption="OWASP Top 10" numberSuffix="%" labelDisplay="wrap" maxLabelWidthPercent="40"  captionAlignment="left"   numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="60" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="1" bgratio="0" startingangle="-160" animation="1"> <set value="45" label="Lack of patch management&#10; process/Patch validation" color="523995"/> <set value="30" label="Lack of secure code - &#10;parameter policy/Validation" color="6a6ab3" /> <set value="15"  label="Lack of security configuration&#10; policy/Validation" color="8d99cd"  /> <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';

var dataStringPieapp4 ='<chart caption="TBD" numDivLines="0" showYAxisValues="0" numberSuffix="%" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F"  basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="ffffff" showpercentvalues="0" bgratio="0" startingangle="-160" animation="1"> <set value="77" label="www.ynhh.org" color="078576"/> <set value="54" label="mychart.ynhhs.org" color="66a36f" /> <set value="45" label="ynhhs.org" color="9cc366" />   <set value="23" label="www.charts.ynhhs.org" color="cbda9a" /><styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles></chart>';

var dataStringPie4 ='<chart caption="Application Name" numberSuffix="%" labelDisplay="wrap"   captionAlignment="left"   numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="100" plotSpacePercent="50" showShadow="0" plotGradientcolor=""  use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="1" bgratio="0" startingangle="-160" animation="1"> <set value="77" label="www.ynhh.org" color="1965ae"/> <set value="52" label="mychart.ynhhs.org" color="4b8ab0" /> <set value="34" label="www.chart.ynhhs.org" color="66b2b1" /> <set value="13" label="chart.ynhhs.org" color="a0d3c0" /> <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles>  </chart>';

var dataStringPie2 ='<chart caption="Operating System" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="60" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="0" bgratio="0" startingangle="-160" animation="1"> <set value="40" label="Windows" color="1965ae"/> <set value="30" label="Linux" color="4b8ab0" /> <set value="20" label="Mac" color="66b2b1"  /> <set value="10" label="OS Undetermined" color="a0d3c0"  /> <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';

var dataStringPie1 ='<chart caption="Severity"   alignCaptionWithCanvas="1" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="0" bgratio="0" startingangle="0" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="10" label="Medium" color="F2B411"  /> <set value="150" label="Low" color="627D32"  /> <set value="100" label="Info" color="005e9d"  />  <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';

var dataStringrem ='<chart caption="" alignCaptionWithCanvas="1" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" legendBorderAlpha="0" legendPosition="right"  legendShadow="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="0" canvasBorderColor="ffffff" showpercentvalues="0" bgratio="0" startingangle="0" animation="1"> <set value="80" label="Open" color="6c66af"/> <set value="20" label="Close" color="c6c4df" />   </chart>';



var dataStringPieWire4 ='<chart caption="SSID" numDivLines="0" showYAxisValues="0" numberSuffix="%" showPlotBorder="0" yAxisMaxValue="100" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="1" showValues="1" showLegend="1"   legendPosition="bottom" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F"  basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="ffffff" showpercentvalues="0" bgratio="0" startingangle="-160" animation="1"> <set value="77" label="WILAN02" color="1965ae"/> <set value="56" label="GUESSLAN01" color="4b8ab0" /> <set value="35" label="GUESSLAN02" color="66b2b1" />  <styles><definition><style name="myCaptionFont" type="font" size="15" font="Calibri" color="7f7f7f" align="left"/></definition><application><apply toObject="Caption" styles="myCaptionFont" /><apply toObject="SubCaption" styles="myCaptionFont" /></application></styles> </chart>';






var dataString21 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="2" label="Lack of Security Configuration Policy / Validation" color="c5b0d5"/> <set value="1" label="Lack of Security Monitoring Policy / Validation" color="dbdb8d"/> <set value="2" label="Lack of Security Protection policy" color="9edae5"/></chart>';

var dataString22 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0"  showLabels="0" showValues="1" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="2" label="Lack of Information/ Facility Security Policies" color="98df8a"/> <set value="1" label="Lack of Secure Code - Parameter Policy / Validation" color="ffbb78"/> <set value="1" label="Lack of Security Protection policy" color="9edae5"/></chart>';

var dataString23 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="1" label="Lack of Information/ Facility Security Policies" color="98df8a"/></chart>';

var dataStringR2 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" licingDistance="35" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="3" label="Lack of Information/ Facility Security Policies" color="98df8a"  alpha="30"  link="rca-1.html"/> <set value="1" label="Lack of secure code - parameter policy / Validation" color="ffbb78" alpha="30"  link="rca-2.html"/> <set value="2" label="Lack of security configuration policy / Validation" color="c5b0d5" alpha="30"  link="rca-3.html"/> <set value="1" label="Lack of security monitoring policy / Validation" color="dbdb8d" alpha="30"  link="rca-4.html"/> <set value="3" label="Lack of Security Protection policy" color="9edae5" isSliced="1" /></chart>';

var dataStringR21 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" licingDistance="35" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="3" label="Lack of Information/ Facility Security Policies" color="98df8a" alpha="30"  link="rca-1.html"/> <set value="1" label="Lack of secure code - parameter policy / Validation" color="ffbb78" isSliced="1" /> <set value="2" label="Lack of security configuration policy / Validation" color="c5b0d5" alpha="30"  link="rca-3.html" /> <set value="1" label="Lack of security monitoring policy / Validation" color="dbdb8d" alpha="30"  link="rca-4.html"/> <set value="3" label="Lack of Security Protection policy" color="9edae5" alpha="30"  link="rca-5.html"/></chart>';

var dataStringR22 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" licingDistance="35" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="3" label="Lack of Information/ Facility Security Policies" color="98df8a" alpha="30"  link="rca-1.html" /> <set value="1" label="Lack of secure code - parameter policy / Validation" color="ffbb78"  alpha="30"  link="rca-2.html" /> <set value="2" label="Lack of security configuration policy / Validation" color="c5b0d5" isSliced="1" /> <set value="1" label="Lack of security monitoring policy / Validation" color="dbdb8d" alpha="30"  link="rca-4.html"/> <set value="3" label="Lack of Security Protection policy" color="9edae5" alpha="30"  link="rca-5.html"/></chart>';

var dataStringR23 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" licingDistance="35" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="3" label="Lack of Information / Facility Security Policies" color="98df8a" alpha="30"  link="rca-1.html" /> <set value="1" label="Lack of secure code - parameter policy / Validation" color="ffbb78"  alpha="30"  link="rca-2.html"/> <set value="2" label="Lack of security configuration policy / Validation" color="c5b0d5"  alpha="30"  link="rca-3.html"/> <set value="1" label="Lack of Security Monitoring Policy / Validation" color="dbdb8d" isSliced="1"/> <set value="3" label="Lack of Security Protection policy" color="9edae5" alpha="30"  link="rca-5.html"/></chart>';

var dataStringR24 ='<chart caption="" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" plotGradientcolor="" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" licingDistance="35" showLegend="1"  legendPosition="RIGHT" rightmargin="20" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="2F2F2F" basefontsize="11" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="1" bgratio="0" startingangle="200" animation="1"> <set value="3" label="Lack of Information/ Facility Security Policies" color="98df8a" isSliced="1"/> <set value="1" label="Lack of secure code - parameter policy / Validation" color="ffbb78"  alpha="30"  link="rca-2.html"/> <set value="2" label="Lack of Security Configuration Policy / Validation" color="c5b0d5"  alpha="30"  link="rca-3.html"/> <set value="1" label="Lack of Security Monitoring Policy / Validation" color="dbdb8d" alpha="30"  link="rca-4.html"/> <set value="3" label="Lack of Security Protection Policy" color="9edae5" alpha="30"  link="rca-5.html"/></chart>';

var dataStringRedPie3 ='<chart caption="Red Team" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" plotGradientcolor="" showShadow="0" defaultCenterLabel="" use3DLighting="0" legendShadow="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right"    numberSuffix=""  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="0" animation="1"> <set value="2" label="Critical" color="A32A2E"/> <set value="6" label="High" color="E87722" /> <set value="6" label="Medium" color="F2B411"  /> <set value="4" label="Low" color="627D32"  /> <set value="2" label="Info" color="005e9d"  />  </chart>';

var dataStringNetPie3 ='<chart caption="Network" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" plotGradientcolor="" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="0" animation="1"> <set value="0" label="Critical" color="A32A2E"/> <set value="0" label="High" color="E87722" /> <set value="10" label="Medium" color="F2B411"  /> <set value="7" label="Low" color="627D32"  /> <set value="3" label="Info" color="005e9d"  />  </chart>';

var dataStringAppPie3 ='<chart caption="Application" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" plotGradientcolor="" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="0" animation="1"> <set value="5" label="Critical" color="A32A2E"/> <set value="3" label="High" color="E87722" /> <set value="6" label="Medium" color="F2B411"  /> <set value="4" label="Low" color="627D32"  /> <set value="7" label="Info" color="005e9d"  />  </chart>';

var dataStringThretPie3 ='<chart caption="Threat Hunting" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" plotGradientcolor="" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="0" animation="1"> <set value="0" label="Critical" color="A32A2E"/> <set value="0" label="High" color="E87722" /> <set value="15" label="Medium" color="F2B411"  /> <set value="4" label="Low" color="627D32"  /> <set value="16" label="Info" color="005e9d"  />  </chart>';

var dataStringNet1Pie3 ='<chart caption="Network" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" plotGradientcolor="" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right"  legendShadow="0" placeValuesInside="1" numberSuffix=""  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="270" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="50" label="Medium" color="F2B411"  /> <set value="80" label="Low" color="627D32"  /> <set value="70" label="Info" color="005e9d"  />  </chart>';

var dataStringApp1Pie3 ='<chart caption="Application" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="270" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="50" label="Medium" color="F2B411"  /> <set value="80" label="Low" color="627D32"  /> <set value="70" label="Info" color="005e9d"  />  </chart>';

var dataStringWirePie3 ='<chart caption="Wireless" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="270" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="50" label="Medium" color="F2B411"  /> <set value="80" label="Low" color="627D32"  /> <set value="70" label="Info" color="005e9d"  />  </chart>';

var dataStringPenePie3 ='<chart caption="Penetratin Testing" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="270" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="50" label="Medium" color="F2B411"  /> <set value="80" label="Low" color="627D32"  /> <set value="70" label="Info" color="005e9d"  />  </chart>';

var dataStringRiskPie3 ='<chart caption="Risk" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="270" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="50" label="Medium" color="F2B411"  /> <set value="80" label="Low" color="627D32"  /> <set value="70" label="Info" color="005e9d"  />  </chart>';

var dataStringArchPie3 ='<chart caption="Architecture" numDivLines="0" showYAxisValues="0" showPlotBorder="0" yAxisMaxValue="170" plotSpacePercent="50" showShadow="0" defaultCenterLabel="" use3DLighting="0" showLabels="0" showValues="1" showLegend="0" legendBorderAlpha="0" legendPosition="right" legendShadow="0"  legendPosition="bottom" rightmargin="0" bgcolor="ECF5FF" bgalpha="70" bordercolor="" basefontcolor="666666" basefontsize="9" bgColor="ffffff" borderThickness="0" borderColor="ffffff" canvasBorderThickness="1" canvasBorderColor="d7dcd2" showpercentvalues="0" bgratio="0" startingangle="270" animation="1"> <set value="20" label="Critical" color="A32A2E"/> <set value="40" label="High" color="E87722" /> <set value="50" label="Medium" color="F2B411"  /> <set value="80" label="Low" color="627D32"  /> <set value="70" label="Info" color="005e9d"  />  </chart>';
