CREATE TABLE [dbo].[APPL_ROLE_PERMSN_GRP] (
    [USER_ROLE_PERMSN_GRP_KEY] INT      IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]              INT      NOT NULL,
    [APPL_ROLE_KEY]            INT      NOT NULL,
    [PERMSN_GRP_KEY]           INT      NOT NULL,
    [CREAT_DT]                 DATETIME NOT NULL,
    [CREAT_USER_ID]            INT      NOT NULL,
    [UPDT_DT]                  DATETIME NULL,
    [UPDT_USER_ID]             INT      NULL,
    CONSTRAINT [PK_APPL_ROLE_PERMSN_GRP] PRIMARY KEY CLUSTERED ([USER_ROLE_PERMSN_GRP_KEY] ASC),
    CONSTRAINT [FK_APPL_ROLE_27] FOREIGN KEY ([APPL_ROLE_KEY]) REFERENCES [dbo].[APPL_ROLE] ([APPL_ROLE_KEY]),
    CONSTRAINT [FK_MSTR_LKP_33] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_PERMSN_GRP_86] FOREIGN KEY ([PERMSN_GRP_KEY]) REFERENCES [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY])
);