CREATE TABLE [dbo].[CLNT_REL_ENGMT_ID] (
    [CLNT_REL_ENGMT_ID_KEY] INT           IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]           INT           NOT NULL,
    [CLNT_ENGMT_CD]         VARCHAR (30)  NOT NULL,
    [SRC_KEY]               INT           NOT NULL,
    [SRC_REL_ENGMT_ID]      VARCHAR (150) NULL,
    [CREAT_DT]              DATETIME      NOT NULL,
    [CREAT_USER_ID]         INT           NOT NULL,
    [UPDT_DT]               DATETIME      NULL,
    [UPDT_USER_ID]          INT           NULL,
    CONSTRAINT [PK_CLNT_REL_ENGMT_ID] PRIMARY KEY CLUSTERED ([CLNT_REL_ENGMT_ID_KEY] ASC),
    CONSTRAINT [FK_CLNT_ENGMT_3] FOREIGN KEY ([CLNT_ENGMT_CD]) REFERENCES [dbo].[CLNT_ENGMT] ([CLNT_ENGMT_CD]),
    CONSTRAINT [FK_MSTR_LKP_5] FOREIGN KEY ([SRC_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_MSTR_LKP_54] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY])
);