CREATE TABLE [dbo].[CLNT_ENGMT_USER_ASGN] (
    [CLNT_ENGMT_USER_ASGN_KEY] INT           IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]              INT           NOT NULL,
    [CLNT_ENGMT_CD]            VARCHAR (30)  NOT NULL,
    [USER_ID]                  INT           NOT NULL,
    [SECUR_SRVC_LIST_CD]       VARCHAR (150) NULL,
    [CREAT_DT]                 DATETIME      NOT NULL,
    [CREAT_USER_ID]            INT           NOT NULL,
    [UPDT_DT]                  DATETIME      NULL,
    [UPDT_USER_ID]             INT           NULL,
    CONSTRAINT [PK_CLNT_ENGMT_USER_ASGN] PRIMARY KEY CLUSTERED ([CLNT_ENGMT_USER_ASGN_KEY] ASC),
    CONSTRAINT [FK_CLNT_ENGMT_63] FOREIGN KEY ([CLNT_ENGMT_CD]) REFERENCES [dbo].[CLNT_ENGMT] ([CLNT_ENGMT_CD]),
    CONSTRAINT [FK_MSTR_LKP_50] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_USER_PRFL_62] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USER_PRFL] ([USER_ID])
);