CREATE TABLE [dbo].[CLNT_VULN_SECUR_CTL] (
    [CLNT_VULN_INSTC_KEY] INT          NOT NULL,
    [REG_CMPLN_CD]        VARCHAR (20) NOT NULL,
    [REG_CMPLN_VER]       VARCHAR (20) NOT NULL,
    [SECUR_CTL_CD]        VARCHAR (20) NOT NULL,
    [ROW_STS_KEY]         INT          NOT NULL,
    [CREAT_DT]            DATETIME     NOT NULL,
    [CREAT_USER_ID]       INT          NOT NULL,
    [UPDT_DT]             DATETIME     NULL,
    [UPDT_USER_ID]        INT          NULL,
    CONSTRAINT [PK_CLNT_VULN_SECUR_CTL] PRIMARY KEY CLUSTERED ([CLNT_VULN_INSTC_KEY] ASC, [REG_CMPLN_CD] ASC, [REG_CMPLN_VER] ASC, [SECUR_CTL_CD] ASC),
    CONSTRAINT [FK_CLNT_VULN_INSTC_83] FOREIGN KEY ([CLNT_VULN_INSTC_KEY]) REFERENCES [dbo].[CLNT_VULN_INSTC] ([CLNT_VULN_INSTC_KEY]),
    CONSTRAINT [FK_MSTR_LKP_79] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_SECUR_CTL_76] FOREIGN KEY ([REG_CMPLN_CD], [REG_CMPLN_VER], [SECUR_CTL_CD]) REFERENCES [dbo].[SECUR_CTL] ([REG_CMPLN_CD], [REG_CMPLN_VER], [SECUR_CTL_CD])
);