CREATE TABLE [dbo].[CLNT_SCHM_LOG] (
    [CLNT_SCHM_LOG_KEY] INT          IDENTITY (1, 1) NOT NULL,
    [ORG_KEY]           INT          NOT NULL,
    [SCHM_STS_DESC]     VARCHAR (40) NULL,
    [ERR_DESC]          TEXT         NULL,
    [CREAT_DT]          DATETIME     NOT NULL,
    CONSTRAINT [PK_CLNT_SCHM_LOG] PRIMARY KEY CLUSTERED ([CLNT_SCHM_LOG_KEY] ASC),
    CONSTRAINT [FK_ORG_115] FOREIGN KEY ([ORG_KEY]) REFERENCES [dbo].[ORG] ([ORG_KEY])
);


GO
CREATE NONCLUSTERED INDEX [IF1_CLNT_SCHM_LOG]
    ON [dbo].[CLNT_SCHM_LOG]([ORG_KEY] ASC);
