CREATE TABLE [dbo].[CVE_SECUR_CTL_MAP] (
    [CVE_ID]        VARCHAR (25) NOT NULL,
    [REG_CMPLN_CD]  VARCHAR (20) NOT NULL,
    [REG_CMPLN_VER] VARCHAR (20) NOT NULL,
    [SECUR_CTL_CD]  VARCHAR (20) NOT NULL,
    [ROW_STS_KEY]   INT          NOT NULL,
    [CREAT_DT]      DATETIME     NOT NULL,
    [CREAT_USER_ID] INT          NOT NULL,
    [UPDT_DT]       DATETIME     NULL,
    [UPDT_USER_ID]  INT          NULL,
    CONSTRAINT [PK_CVE_SECUR_CTL_MAP] PRIMARY KEY CLUSTERED ([CVE_ID] ASC, [REG_CMPLN_CD] ASC, [REG_CMPLN_VER] ASC, [SECUR_CTL_CD] ASC),
    CONSTRAINT [FK_CVE_8] FOREIGN KEY ([CVE_ID]) REFERENCES [dbo].[CVE] ([CVE_ID]),
    CONSTRAINT [FK_MSTR_LKP_78] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_SECUR_CTL_9] FOREIGN KEY ([REG_CMPLN_CD], [REG_CMPLN_VER], [SECUR_CTL_CD]) REFERENCES [dbo].[SECUR_CTL] ([REG_CMPLN_CD], [REG_CMPLN_VER], [SECUR_CTL_CD])
);