CREATE TABLE [dbo].[ETL_ERR_LOG] (
    [ETL_ERR_LOG_KEY] INT            IDENTITY (1, 1) NOT NULL,
    [ETL_AUD_LOG_KEY] INT            NOT NULL,
    [ERR_LOG_DT]      DATETIME       NULL,
    [ERR_CD]          VARCHAR (150)  NULL,
    [ERR_MSG_TXT]     VARCHAR (1000) NULL,
    [ERR_REC_TXT]     VARCHAR (2000) NULL,
    CONSTRAINT [PK_ETL_ERR_LOG] PRIMARY KEY CLUSTERED ([ETL_ERR_LOG_KEY] ASC),
    CONSTRAINT [FK_ETL_AUD_LOG_11] FOREIGN KEY ([ETL_AUD_LOG_KEY]) REFERENCES [dbo].[ETL_AUD_LOG] ([ETL_AUD_LOG_KEY])
);