CREATE TABLE [dbo].[NTF_MSG] (
    [NTF_MSG_KEY]   INT           IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]   INT           NOT NULL,
    [NTF_TYP_NM]    VARCHAR (255) NOT NULL,
    [MSG_SBJ_TXT]   VARCHAR (255) NULL,
    [MSG_CNTN_TXT]  TEXT          NULL,
    [CREAT_DT]      DATETIME      NOT NULL,
    [CREAT_USER_ID] INT           NOT NULL,
    [UPDT_DT]       DATETIME      NULL,
    [UPDT_USER_ID]  INT           NULL,
    CONSTRAINT [PK_NTF_MSG] PRIMARY KEY CLUSTERED ([NTF_MSG_KEY] ASC),
    CONSTRAINT [FK_MSTR_LKP_35] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY])
);