CREATE TABLE [dbo].[ORG_REL_ID] (
    [ORG_REL_ID_KEY] INT           IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]    INT           NOT NULL,
    [ORG_KEY]        INT           NOT NULL,
    [SRC_KEY]        INT           NOT NULL,
    [SRC_CLNT_ID]    VARCHAR (150) NULL,
    [CREAT_DT]       DATETIME      NOT NULL,
    [CREAT_USER_ID]  INT           NOT NULL,
    [UPDT_DT]        DATETIME      NULL,
    [UPDT_USER_ID]   INT           NULL,
    CONSTRAINT [PK_ORG_REL_ID] PRIMARY KEY CLUSTERED ([ORG_REL_ID_KEY] ASC),
    CONSTRAINT [FK_MSTR_LKP_51] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_MSTR_LKP_67] FOREIGN KEY ([SRC_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_ORG_64] FOREIGN KEY ([ORG_KEY]) REFERENCES [dbo].[ORG] ([ORG_KEY])
);