CREATE TABLE [dbo].[OS_CATGY] (
    [OS_CATGY_KEY]  INT           IDENTITY (1, 1) NOT NULL,
    [OS_CATGY_NM]   VARCHAR (150) NULL,
    [CREAT_DT]      DATETIME      NOT NULL,
    [CREAT_USER_ID] INT           NOT NULL,
    [UPDT_DT]       DATETIME      NULL,
    [UPDT_USER_ID]  INT           NULL,
    CONSTRAINT [PK_OS_CATGY] PRIMARY KEY CLUSTERED ([OS_CATGY_KEY] ASC)
);