CREATE TABLE [dbo].[PERMSN] (
    [PERMSN_KEY]     INT            IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]    INT            NOT NULL,
    [PAR_PERMSN_KEY] INT            NULL,
    [PERMSN_TYP_KEY] INT            NOT NULL,
    [PERMSN_NM]      VARCHAR (100)  NOT NULL,
    [PERMSN_DESC]    VARCHAR (1000) NULL,
    [DSPL_TXT]       VARCHAR (100)  NULL,
    [CHLD_XST_IND]   INT            DEFAULT ((0)) NOT NULL,
    [SEQ_ORDR]       INT            DEFAULT ((0)) NOT NULL,
    [CREAT_DT]       DATETIME       NOT NULL,
    [CREAT_USER_ID]  INT            NOT NULL,
    [UPDT_DT]        DATETIME       NULL,
    [UPDT_USER_ID]   INT            NULL,
    CONSTRAINT [PK_PERMSN] PRIMARY KEY CLUSTERED ([PERMSN_KEY] ASC),
    CONSTRAINT [FK_MSTR_LKP_80] FOREIGN KEY ([PERMSN_TYP_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_MSTR_LKP_92] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_PERMSN_68] FOREIGN KEY ([PAR_PERMSN_KEY]) REFERENCES [dbo].[PERMSN] ([PERMSN_KEY])
);