CREATE TABLE [dbo].[PERMSN_GRP_ASSOC] (
    [PERMSN_GRP_ASSOC_KEY] INT      IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]          INT      NOT NULL,
    [PERMSN_GRP_KEY]       INT      NOT NULL,
    [PERMSN_KEY]           INT      NOT NULL,
    [MDUL_ID]              INT      NULL,
    [MNU_ID]               INT      NOT NULL,
    [SUB_MNU_ID]           INT      NOT NULL,
    [CREAT_DT]             DATETIME NOT NULL,
    [CREAT_USER_ID]        INT      NOT NULL,
    [UPDT_DT]              DATETIME NULL,
    [UPDT_USER_ID]         INT      NULL,
    CONSTRAINT [PK_PERMSN_GRP_ASSOC] PRIMARY KEY CLUSTERED ([PERMSN_GRP_ASSOC_KEY] ASC),
    CONSTRAINT [FK_MSTR_LKP_31] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_PERMSN_69] FOREIGN KEY ([PERMSN_KEY]) REFERENCES [dbo].[PERMSN] ([PERMSN_KEY]),
    CONSTRAINT [FK_PERMSN_GRP_85] FOREIGN KEY ([PERMSN_GRP_KEY]) REFERENCES [dbo].[PERMSN_GRP] ([PERMSN_GRP_KEY])
);