CREATE TABLE [dbo].[SECUR_CTL_MAP] (
    [SECUR_CTL_MAP_KEY] INT          IDENTITY (1, 1) NOT NULL,
    [PRI_REG_CMPLN_CD]  VARCHAR (20) NOT NULL,
    [PRI_REG_CMPLN_VER] VARCHAR (20) NOT NULL,
    [PRI_SECUR_CTL_CD]  VARCHAR (20) NOT NULL,
    [SEC_REG_CMPLN_CD]  VARCHAR (20) NOT NULL,
    [SEC_REG_CMPLN_VER] VARCHAR (20) NOT NULL,
    [SEC_SECUR_CTL_CD]  VARCHAR (20) NOT NULL,
    [CREAT_DT]          DATETIME     NOT NULL,
    [CREAT_USER_ID]     INT          NOT NULL,
    [UPDT_DT]           DATETIME     NULL,
    [UPDT_USER_ID]      INT          NULL,
    CONSTRAINT [PK_SECUR_CTL_MAP] PRIMARY KEY CLUSTERED ([SECUR_CTL_MAP_KEY] ASC),
    CONSTRAINT [FK_SECUR_CTL_10] FOREIGN KEY ([PRI_REG_CMPLN_CD], [PRI_REG_CMPLN_VER], [PRI_SECUR_CTL_CD]) REFERENCES [dbo].[SECUR_CTL] ([REG_CMPLN_CD], [REG_CMPLN_VER], [SECUR_CTL_CD]),
    CONSTRAINT [FK_SECUR_CTL_7] FOREIGN KEY ([SEC_REG_CMPLN_CD], [SEC_REG_CMPLN_VER], [SEC_SECUR_CTL_CD]) REFERENCES [dbo].[SECUR_CTL] ([REG_CMPLN_CD], [REG_CMPLN_VER], [SECUR_CTL_CD]),
    CONSTRAINT [AK1_SECUR_CTL_MAP] UNIQUE NONCLUSTERED ([PRI_REG_CMPLN_CD] ASC, [PRI_REG_CMPLN_VER] ASC, [PRI_SECUR_CTL_CD] ASC, [SEC_REG_CMPLN_CD] ASC, [SEC_REG_CMPLN_VER] ASC, [SEC_SECUR_CTL_CD] ASC)
);