CREATE TABLE [dbo].[SECUR_PKG_OFR] (
    [SECUR_PKG_CD]  VARCHAR (10) NOT NULL,
    [SECUR_SRVC_CD] VARCHAR (10) NOT NULL,
    [ROW_STS_KEY]   INT          NOT NULL,
    [CREAT_DT]      DATETIME     NOT NULL,
    [CREAT_USER_ID] INT          NOT NULL,
    [UPDT_DT]       DATETIME     NULL,
    [UPDT_USER_ID]  INT          NULL,
    CONSTRAINT [PK_SECUR_PKG_OFR] PRIMARY KEY CLUSTERED ([SECUR_PKG_CD] ASC, [SECUR_SRVC_CD] ASC),
    CONSTRAINT [FK_MSTR_LKP_53] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_SECUR_PKG_45] FOREIGN KEY ([SECUR_PKG_CD]) REFERENCES [dbo].[SECUR_PKG] ([SECUR_PKG_CD]),
    CONSTRAINT [FK_SECUR_SRVC_46] FOREIGN KEY ([SECUR_SRVC_CD]) REFERENCES [dbo].[SECUR_SRVC] ([SECUR_SRVC_CD])
);