CREATE TABLE [dbo].[SECUR_SRVC] (
    [SECUR_SRVC_CD]   VARCHAR (10)   NOT NULL,
    [ROW_STS_KEY]     INT            NOT NULL,
    [SECUR_SRVC_NM]   VARCHAR (150)  NOT NULL,
    [SECUR_SRVC_DESC] VARCHAR (1000) NULL,
    [CREAT_DT]        DATETIME       NOT NULL,
    [CREAT_USER_ID]   INT            NOT NULL,
    [UPDT_DT]         DATETIME       NULL,
    [UPDT_USER_ID]    INT            NULL,
    CONSTRAINT [PK_SECUR_SRVC] PRIMARY KEY CLUSTERED ([SECUR_SRVC_CD] ASC),
    CONSTRAINT [FK_MSTR_LKP_55] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY])
);