CREATE TABLE [dbo].[SECUR_PKG] (
    [SECUR_PKG_CD]   VARCHAR (10)   NOT NULL,
    [ROW_STS_KEY]    INT            NOT NULL,
    [SECUR_PKG_NM]   VARCHAR (150)  NOT NULL,
    [SECUR_PKG_DESC] VARCHAR (1000) NULL,
    [CREAT_DT]       DATETIME       NOT NULL,
    [CREAT_USER_ID]  INT            NOT NULL,
    [UPDT_DT]        DATETIME       NULL,
    [UPDT_USER_ID]   INT            NULL,
    CONSTRAINT [PK_SECUR_PKG] PRIMARY KEY CLUSTERED ([SECUR_PKG_CD] ASC),
    CONSTRAINT [FK_MSTR_LKP_49] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY])
);