CREATE TABLE [dbo].[ST_CD] (
    [ST_CD_KEY]     INT           IDENTITY (1, 1) NOT NULL,
    [ST_CD]         VARCHAR (10)  NOT NULL,
    [CNTRY_CD]      VARCHAR (10)  NULL,
    [ST_NM]         VARCHAR (150) NOT NULL,
    [CREAT_DT]      DATETIME      NOT NULL,
    [CREAT_USER_ID] INT           NOT NULL,
    [UPDT_DT]       DATETIME      NULL,
    [UPDT_USER_ID]  INT           NULL,
    CONSTRAINT [PK_ST_CD] PRIMARY KEY CLUSTERED ([ST_CD_KEY] ASC),
    CONSTRAINT [FK_CNTRY_CD_29] FOREIGN KEY ([CNTRY_CD]) REFERENCES [dbo].[CNTRY_CD] ([CNTRY_CD])
);