CREATE TABLE [dbo].[USER_CLNT_SRVC_ASGN] (
    [USER_CLNT_SRVC_ASGN_KEY] INT          IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]             INT          NOT NULL,
    [CLNT_ENGMT_CD]           VARCHAR (30) NOT NULL,
    [SECUR_SRVC_CD]           VARCHAR (10) NOT NULL,
    [USER_ID]                 INT          NOT NULL,
    [USER_STRT_DT]            DATETIME     NULL,
    [USER_END_DT]             DATETIME     NULL,
    [CREAT_DT]                DATETIME     NOT NULL,
    [CREAT_USER_ID]           INT          NOT NULL,
    [UPDT_DT]                 DATETIME     NULL,
    [UPDT_USER_ID]            INT          NULL,
    CONSTRAINT [PK_USER_CLNT_SRVC_ASGN] PRIMARY KEY CLUSTERED ([USER_CLNT_SRVC_ASGN_KEY] ASC),
    CONSTRAINT [FK_CLNT_SECUR_SRVC_ENGMT_65] FOREIGN KEY ([CLNT_ENGMT_CD], [SECUR_SRVC_CD]) REFERENCES [dbo].[CLNT_SECUR_SRVC_ENGMT] ([CLNT_ENGMT_CD], [SECUR_SRVC_CD]),
    CONSTRAINT [FK_MSTR_LKP_52] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_SECUR_SRVC_42] FOREIGN KEY ([SECUR_SRVC_CD]) REFERENCES [dbo].[SECUR_SRVC] ([SECUR_SRVC_CD]),
    CONSTRAINT [FK_USER_PRFL_66] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USER_PRFL] ([USER_ID])
);