CREATE TABLE [dbo].[USER_APPL_ROLE] (
    [USER_APPL_ROLE_KEY] INT      IDENTITY (1, 1) NOT NULL,
    [ROW_STS_KEY]        INT      NOT NULL,
    [APPL_ROLE_KEY]      INT      NOT NULL,
    [USER_ID]            INT      NOT NULL,
    [CREAT_DT]           DATETIME NOT NULL,
    [CREAT_USER_ID]      INT      NOT NULL,
    [UPDT_DT]            DATETIME NULL,
    [UPDT_USER_ID]       INT      NULL,
    CONSTRAINT [PK_USER_APPL_ROLE] PRIMARY KEY CLUSTERED ([USER_APPL_ROLE_KEY] ASC),
    CONSTRAINT [FK_APPL_ROLE_28] FOREIGN KEY ([APPL_ROLE_KEY]) REFERENCES [dbo].[APPL_ROLE] ([APPL_ROLE_KEY]),
    CONSTRAINT [FK_MSTR_LKP_71] FOREIGN KEY ([ROW_STS_KEY]) REFERENCES [dbo].[MSTR_LKP] ([MSTR_LKP_KEY]),
    CONSTRAINT [FK_USER_PRFL_32] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USER_PRFL] ([USER_ID])
);