CREATE TABLE [dbo].[USER_SESS_LOG] (
    [USER_SESS_INFO_KEY] INT           IDENTITY (1, 1) NOT NULL,
    [USER_ID]            INT           NOT NULL,
    [EMAIL_ID]           VARCHAR (150) NULL,
    [SESS_ID]            VARCHAR (500) NULL,
    [LST_ACT_DT]         DATETIME      NULL,
    CONSTRAINT [PK_USER_SESS_LOG] PRIMARY KEY CLUSTERED ([USER_SESS_INFO_KEY] ASC),
    CONSTRAINT [FK_USER_PRFL_40] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USER_PRFL] ([USER_ID])
);