CREATE TABLE [dbo].[VULN] (
    [VULN_NM]       VARCHAR (255) NOT NULL,
    [VULN_CATGY_CD] VARCHAR (10)  NULL,
    [CREAT_DT]      DATETIME      NOT NULL,
    [CREAT_USER_ID] INT           NOT NULL,
    [UPDT_DT]       DATETIME      NULL,
    [UPDT_USER_ID]  INT           NULL,
    CONSTRAINT [PK_VULN] PRIMARY KEY CLUSTERED ([VULN_NM] ASC),
    CONSTRAINT [FK_VULN_CATGY_118] FOREIGN KEY ([VULN_CATGY_CD]) REFERENCES [dbo].[VULN_CATGY] ([VULN_CATGY_CD])
);


GO
CREATE NONCLUSTERED INDEX [IF1_VULN]
    ON [dbo].[VULN]([VULN_CATGY_CD] ASC);

