CREATE TABLE [dbo].[VULN_INSTC_STS] (
    [VULN_INSTC_STS_CD] VARCHAR (3)   NOT NULL,
    [VULN_INSTC_STS_NM] VARCHAR (150) NULL,
    [CREAT_DT]          DATETIME      NOT NULL,
    [CREAT_USER_ID]     INT           NOT NULL,
    [UPDT_DT]           DATETIME      NULL,
    [UPDT_USER_ID]      INT           NULL,
    CONSTRAINT [PK_VULN_INSTC_STS] PRIMARY KEY CLUSTERED ([VULN_INSTC_STS_CD] ASC)
);