
CREATE  FUNCTION [dbo].[fnGetServiceNameBycode]
(	
	@SECUR_SRVC_CD VARCHAR(10)
)
RETURNS VARCHAR(150)
AS
BEGIN
    DECLARE @EntityID VARCHAR(150)
      
      SELECT @EntityID = SECUR_SRVC_NM FROM SECUR_SRVC 
      WHERE	 SECUR_SRVC_CD = @SECUR_SRVC_CD

    RETURN @EntityID
END

