
CREATE FUNCTION dbo.fnGetSecurCtlMap(@REG_CMPLN_CD AS VARCHAR(20), @REG_CMPLN_VER AS VARCHAR(20), @SECUR_CTL_CD AS VARCHAR(20))
    RETURNS TABLE
AS
RETURN

	SELECT REG_CMPLN_CD, REG_CMPLN_VER, SECUR_CTL_CD
	FROM
	(
	  SELECT PRI_REG_CMPLN_CD AS REG_CMPLN_CD, PRI_REG_CMPLN_VER AS REG_CMPLN_VER, PRI_SECUR_CTL_CD AS SECUR_CTL_CD 
	  FROM [dbo].SECUR_CTL_MAP
			WHERE PRI_REG_CMPLN_CD = @REG_CMPLN_CD
				AND PRI_REG_CMPLN_VER = @REG_CMPLN_VER
				AND PRI_SECUR_CTL_CD = @SECUR_CTL_CD
	  UNION
	  SELECT SEC_REG_CMPLN_CD AS REG_CMPLN_CD, SEC_REG_CMPLN_VER AS REG_CMPLN_VER, SEC_SECUR_CTL_CD AS SECUR_CTL_CD 
	  FROM [dbo].SECUR_CTL_MAP 
			WHERE PRI_REG_CMPLN_CD = @REG_CMPLN_CD
				AND PRI_REG_CMPLN_VER = @REG_CMPLN_VER
				AND PRI_SECUR_CTL_CD = @SECUR_CTL_CD
	) SecurCtldata
