CREATE TABLE [stg].[CISCO_PEN_TST_STG] (
    [ID]                     VARCHAR (50)    NULL,
    [SEV]                    INT             NULL,
    [SEV_LBL]                VARCHAR (150)   NULL,
    [PRBL]                   INT             NULL,
    [PRBL_LBL]               VARCHAR (150)   NULL,
    [URL]                    VARCHAR (2000)  NULL,
    [DESC]                   TEXT            NULL,
    [CREAT_AT]               DATETIME        NULL,
    [STS]                    VARCHAR (150)   NULL,
    [IP]                     VARCHAR (255)   NULL,
    [IP_AS_INTG]             BIGINT          NULL,
    [PORT]                   INT             NULL,
    [PRTCL]                  VARCHAR (255)   NULL,
    [CVSS_BAS]               DECIMAL (10, 2) NULL,
    [CVSS_TMPRL]             DECIMAL (10, 2) NULL,
    [HST]                    VARCHAR (255)   NULL,
    [OS]                     VARCHAR (255)   NULL,
    [SCOR]                   INT             NULL,
    [SCOR_LBL]               VARCHAR (150)   NULL,
    [RMDTN_EFFRT]            INT             NULL,
    [RMDTN_EFFRT_LBL]        VARCHAR (150)   NULL,
    [PROJ_ID]                VARCHAR (150)   NULL,
    [PROJ_STRT_DT]           DATETIME        NULL,
    [PROJ_END_DT]            DATETIME        NULL,
    [VULN_CLSS]              VARCHAR (255)   NULL,
    [CVE]                    VARCHAR (2000)  NULL,
    [CATGY]                  VARCHAR (255)   NULL,
    [DTL]                    TEXT            NULL,
    [SECUR_IMP]              TEXT            NULL,
    [MITG_FCT]               TEXT            NULL,
    [SOLN]                   TEXT            NULL,
    [REPRD_STEP]             TEXT            NULL,
    [REPRD_NOTE]             TEXT            NULL,
    [CSTM_FLD_1]             VARCHAR (1000)  NULL,
    [CSTM_FLD_2]             VARCHAR (1000)  NULL,
    [CSTM_FLD_3]             VARCHAR (1000)  NULL,
    [CSTM_FLD_4]             VARCHAR (1000)  NULL,
    [CSTM_COL_TYP]           VARCHAR (1000)  NULL,
    [CSTM_COL_LBL]           VARCHAR (1000)  NULL,
    [APPL_FL_UPLOAD_LOG_KEY] INT             NOT NULL,
    [CREAT_DT]               DATETIME        NOT NULL,
    [CREAT_USER_ID]          INT             NOT NULL
);