CREATE TABLE [stg].[CMN_FMT_V1_STG] (
    [SRC_VULN_SCAN_ID]       VARCHAR (150)   NULL,
    [SRC_VULN_SCAN_STRT_DT]  DATETIME        NULL,
    [SRC_VULN_SCAN_END_DT]   DATETIME        NULL,
    [SRC_VULN_INSTC_ID]      VARCHAR (150)   NULL,
    [SRC_VULN_ID]            VARCHAR (150)   NULL,
    [VULN_NM]                VARCHAR (255)   NOT NULL,
    [VULN_DESC]              TEXT            NULL,
    [VULN_CREAT_DT]          DATETIME        NOT NULL,
    [VULN_SEV_CD]            VARCHAR (3)     NULL,
    [VULN_SEV_NM]            VARCHAR (150)   NULL,
    [VULN_IMP_CD]            VARCHAR (3)     NULL,
    [VULN_IMP_NM]            VARCHAR (150)   NULL,
    [RISK_PRBL_CD]           VARCHAR (3)     NULL,
    [RISK_PRBL_NM]           VARCHAR (150)   NULL,
    [RMDTN_CST_EFFRT_CD]     VARCHAR (3)     NULL,
    [RMDTN_CST_EFFRT_NM]     VARCHAR (150)   NULL,
    [OWASP_CD]               VARCHAR (10)    NULL,
    [IPADR]                  VARCHAR (39)    NULL,
    [PORT_NBR]               INT             NULL,
    [HST_NM]                 VARCHAR (150)   NULL,
    [NTWK_NM]                VARCHAR (150)   NULL,
    [PRTCL_NM]               VARCHAR (255)   NULL,
    [NETBIOS_NM]             VARCHAR (150)   NULL,
    [MAC_ADR_NM]             VARCHAR (150)   NULL,
    [APPL_URL]               NVARCHAR (2000) NULL,
    [SFTW_NM]                VARCHAR (150)   NULL,
    [CVE_ID]                 VARCHAR (25)    NULL,
    [SRC_ADVS_TXT]           VARCHAR (1024)  NULL,
    [DOM_NM]                 VARCHAR (150)   NULL,
    [OS_NM]                  VARCHAR (150)   NULL,
    [VULN_BAS_SCOR]          DECIMAL (10, 2) NULL,
    [VULN_EXPLT_SUB_SCOR]    DECIMAL (10, 2) NULL,
    [VULN_IMP_SUB_SCOR]      DECIMAL (10, 2) NULL,
    [VULN_TMPRL_SCOR]        DECIMAL (10, 2) NULL,
    [VULN_ENV_SCOR]          DECIMAL (10, 2) NULL,
    [VULN_VCTR_TXT]          VARCHAR (100)   NULL,
    [RECOM_COMMT_TXT]        TEXT            NULL,
    [VULN_IMP_COMMT_TXT]     TEXT            NULL,
    [ROOT_CAUS_COMMT_TXT]    TEXT            NULL,
    [VULN_TECH_COMMT_TXT]    TEXT            NULL,
    [APPL_FL_UPLOAD_LOG_KEY] INT             NOT NULL,
    [CREAT_DT]               DATETIME        NOT NULL,
    [CREAT_USER_ID]          INT             NOT NULL
);