CREATE TABLE [stg].[SECUR_CTL_MAP_STG] (
    [PRI_REG_CMPLN_CD]  VARCHAR (20) NOT NULL,
    [PRI_REG_CMPLN_VER] VARCHAR (20) NOT NULL,
    [PRI_SECUR_CTL_CD]  VARCHAR (20) NOT NULL,
    [SEC_REG_CMPLN_CD]  VARCHAR (20) NOT NULL,
    [SEC_REG_CMPLN_VER] VARCHAR (20) NOT NULL,
    [SEC_SECUR_CTL_CD]  VARCHAR (20) NOT NULL,
    [CREAT_DT]          DATETIME     NOT NULL,
    [CREAT_USER_ID]     INT          NOT NULL,
    CONSTRAINT [PK_SECUR_CTL_MAP_STG] PRIMARY KEY CLUSTERED ([PRI_REG_CMPLN_CD] ASC, [PRI_REG_CMPLN_VER] ASC, [PRI_SECUR_CTL_CD] ASC, [SEC_REG_CMPLN_CD] ASC, [SEC_REG_CMPLN_VER] ASC, [SEC_SECUR_CTL_CD] ASC)
);
