CREATE TABLE [stg].[TRIPWIRE_IP360_STG] (
    [AUD_ID]            INT            NOT NULL,
    [NTWK_ID]           INT            NOT NULL,
    [NTWK_NM]           VARCHAR (256)  NOT NULL,
    [NTWK_GRP_NM]       VARCHAR (128)  NULL,
    [SCANPROFILE_ID]    INT            NOT NULL,
    [STRT_DT]           DATETIME       NULL,
    [END_DT]            DATETIME       NULL,
    [VULN_ID]           INT            NOT NULL,
    [VULN_NM]           VARCHAR (512)  NULL,
    [DESC]              TEXT           NULL,
    [ADVS]              VARCHAR (1024) NULL,
    [RISK]              VARCHAR (32)   NULL,
    [SKL]               VARCHAR (32)   NULL,
    [STRG]              VARCHAR (32)   NULL,
    [PUBL_DT]           DATETIME       NULL,
    [GUID]              INT            NULL,
    [APPL_NM]           VARCHAR (256)  NULL,
    [PORT]              INT            NULL,
    [PRTCL]             VARCHAR (64)   NULL,
    [MAX_CVSS_BAS_SCOR] DECIMAL (3, 1) NULL,
    [VNE_ID]            INT            NOT NULL,
    [IP]                VARCHAR (39)   NULL,
    [HST_NM]            VARCHAR (128)  NULL,
    [NETBIOS_NM]        VARCHAR (128)  NULL,
    [DOM_NM]            VARCHAR (128)  NULL,
    [OS_NM]             VARCHAR (128)  NULL,
    [MAC_ADR]           VARCHAR (32)   NULL,
    [IP_NBR]            BIGINT         NULL,
    [CREAT_DT]          DATETIME       NOT NULL,
    [CREAT_USER_ID]     INT            NOT NULL
);
