CREATE PROCEDURE [dbo].[Analyst_GetEngmtAnalystWorkList]
(
	@PiUserID			INTEGER,
	@OrgName			VARCHAR(150),
	@CLNT_ENGMT_CD		VARCHAR(30),	
	@CLNT_ENGMT_NM		VARCHAR(150),
	@SECUR_SRVC_NM		VARCHAR(150),
	@STRT_DT			VARCHAR(10),
	@END_DT				VARCHAR(10),
	@PiUserType			INTEGER,
	@UPDT_DT			VARCHAR(10),
	@Status				VARCHAR(50),	
	@PvcFlag			VARCHAR(1)
)
AS
BEGIN


BEGIN TRY
SET NOCOUNT ON

IF @PvcFlag = 'A' -- Analyst


BEGIN

	SELECT  [Client NAME],CLNT_ORG_KEY, CLNT_ENGMT_CD,CLNT_ENGMT_NM,SECUR_SRVC_NM,SECUR_SRVC_CD,
			FL_LCK_IND, [Start Date],[End Date], UpdatedDate,
			SRVC_ENGMT_STS_KEY,ENGMT_STS_KEY, ReviewStatus,CREAT_DT,UPDT_DT,ORG_SCHM FROM
	(SELECT  DISTINCT H.ORG_NM [Client NAME],B.CLNT_ORG_KEY, A.CLNT_ENGMT_CD,B.CLNT_ENGMT_NM,D.SECUR_SRVC_NM,D.SECUR_SRVC_CD,
			A.FL_LCK_IND,A.SRVC_EST_STRT_DT [Start Date],A.SRVC_EST_END_DT [End Date],A.UPDT_DT UpdatedDate,
			A.SRVC_ENGMT_STS_KEY,B.ENGMT_STS_KEY,I.LKP_ENTY_NM ReviewStatus,B.CREAT_DT,B.UPDT_DT,H.ORG_SCHM
	FROM	CLNT_SECUR_SRVC_ENGMT		A
	JOIN	CLNT_ENGMT					B
	ON		A.CLNT_ENGMT_CD			=	B.CLNT_ENGMT_CD
	JOIN	SECUR_SRVC					D
	ON		D.SECUR_SRVC_CD			=	A.SECUR_SRVC_CD
	JOIN	USER_CLNT_SRVC_ASGN			G
	ON		B.CLNT_ENGMT_CD			=	G.CLNT_ENGMT_CD
	AND		D.SECUR_SRVC_CD			=   G.SECUR_SRVC_CD
	JOIN	ORG							H
	ON		H.ORG_KEY				=	B.CLNT_ORG_KEY 
	JOIN	MSTR_LKP					I
	ON		I.MSTR_LKP_KEY			=   A.SRVC_ENGMT_STS_KEY
	WHERE	G.USER_ID				=   @PiUserID 
	AND		ISNULL(H.ORG_NM,'') LIKE CASE WHEN @OrgName = '' THEN	ISNULL(H.ORG_NM,'') ELSE '%' + @OrgName + '%' END
	AND		ISNULL(A.CLNT_ENGMT_CD,'') LIKE CASE WHEN @CLNT_ENGMT_CD = '' THEN	A.CLNT_ENGMT_CD ELSE '%' + @CLNT_ENGMT_CD +'%' END	
	AND		ISNULL(B.CLNT_ENGMT_NM,'') LIKE CASE WHEN @CLNT_ENGMT_NM = '' THEN	B.CLNT_ENGMT_NM ELSE '%' + @CLNT_ENGMT_NM + '%'   END	
	AND		ISNULL(D.SECUR_SRVC_NM,'') LIKE CASE WHEN @SECUR_SRVC_NM = '' THEN	D.SECUR_SRVC_NM ELSE '%' + @SECUR_SRVC_NM + '%' END
	AND		CONVERT(VARCHAR(20),A.SRVC_EST_STRT_DT,101)	 = CASE WHEN @STRT_DT  = '' THEN CONVERT(VARCHAR(20),A.SRVC_EST_STRT_DT,101)  ELSE @STRT_DT END
	AND		CONVERT(VARCHAR(20),A.SRVC_EST_END_DT,101)	 = CASE WHEN @END_DT  = '' THEN CONVERT(VARCHAR(20),A.SRVC_EST_END_DT,101)  ELSE @END_DT END
	AND		CONVERT(VARCHAR(20),ISNULL(A.UPDT_DT,''),101)	 = CASE WHEN @UPDT_DT  = '' THEN CONVERT(VARCHAR(20),ISNULL(A.UPDT_DT,''),101)  ELSE  @UPDT_DT END
	AND		ISNULL(I.LKP_ENTY_NM ,'') =  CASE WHEN @Status = '' THEN	I.LKP_ENTY_NM  ELSE @Status END		
	AND		A.ROW_STS_KEY	= 1) A
	
	ORDER BY CASE WHEN ISNULL(UPDT_DT,'') ='' THEN CREAT_DT ELSE UPDT_DT END  DESC
	
END

IF @PvcFlag = 'E' -- Engmt Lead
BEGIN
	
	SELECT   [Client NAME],CLNT_ORG_KEY, CLNT_ENGMT_CD,CLNT_ENGMT_NM,SECUR_SRVC_NM,SECUR_SRVC_CD,
			FL_LCK_IND, [Start Date],[End Date], UpdatedDate,
			SRVC_ENGMT_STS_KEY,ENGMT_STS_KEY, ReviewStatus,CREAT_DT,UPDT_DT,ORG_SCHM  FROM
	(
	SELECT   DISTINCT H.ORG_NM [Client NAME],B.CLNT_ORG_KEY, A.CLNT_ENGMT_CD,B.CLNT_ENGMT_NM,D.SECUR_SRVC_NM,D.SECUR_SRVC_CD,
			A.FL_LCK_IND,A.SRVC_EST_STRT_DT [Start Date],A.SRVC_EST_END_DT [End Date],A.UPDT_DT UpdatedDate,
			A.SRVC_ENGMT_STS_KEY,B.ENGMT_STS_KEY,I.LKP_ENTY_NM ReviewStatus,B.CREAT_DT,B.UPDT_DT,H.ORG_SCHM
	FROM	CLNT_SECUR_SRVC_ENGMT		A
	JOIN	CLNT_ENGMT					B
	ON		A.CLNT_ENGMT_CD			=	B.CLNT_ENGMT_CD
	JOIN	SECUR_SRVC					D
	ON		D.SECUR_SRVC_CD			=	A.SECUR_SRVC_CD
	JOIN	CLNT_ENGMT_USER_ASGN		G
	ON		B.CLNT_ENGMT_CD			=	G.CLNT_ENGMT_CD
	JOIN	ORG							H
	ON		H.ORG_KEY				=	B.CLNT_ORG_KEY
	JOIN	MSTR_LKP					I
	ON		I.MSTR_LKP_KEY			=   A.SRVC_ENGMT_STS_KEY
	WHERE	G.USER_ID				=	@PiUserID
	AND		ISNULL(H.ORG_NM,'')		   LIKE CASE WHEN @OrgName = ''		  THEN	ISNULL(H.ORG_NM,'') ELSE '%' + @OrgName +'%' END
	AND		ISNULL(A.CLNT_ENGMT_CD,'') LIKE CASE WHEN @CLNT_ENGMT_CD = '' THEN	A.CLNT_ENGMT_CD ELSE '%' + @CLNT_ENGMT_CD +'%' END	
	AND		ISNULL(B.CLNT_ENGMT_NM,'') LIKE CASE WHEN @CLNT_ENGMT_NM = '' THEN	B.CLNT_ENGMT_NM ELSE '%' + @CLNT_ENGMT_NM + '%' END	
	AND		ISNULL(D.SECUR_SRVC_NM,'') LIKE CASE WHEN @SECUR_SRVC_NM = '' THEN	D.SECUR_SRVC_NM ELSE '%' + @SECUR_SRVC_NM + '%' END
	AND		CONVERT(VARCHAR(20),A.SRVC_EST_STRT_DT,101)	 = CASE WHEN @STRT_DT  = '' THEN CONVERT(VARCHAR(20),A.SRVC_EST_STRT_DT,101)  ELSE @STRT_DT END
	AND		CONVERT(VARCHAR(20),A.SRVC_EST_END_DT,101)	 = CASE WHEN @END_DT  = ''  THEN CONVERT(VARCHAR(20),A.SRVC_EST_END_DT,101)  ELSE @END_DT END
	AND		CONVERT(VARCHAR(20),ISNULL(A.UPDT_DT,''),101)	 = CASE WHEN @UPDT_DT  = '' THEN CONVERT(VARCHAR(20),ISNULL(A.UPDT_DT,''),101)  ELSE  @UPDT_DT END
	AND		ISNULL(I.LKP_ENTY_NM ,'') =  CASE WHEN @Status = '' THEN	I.LKP_ENTY_NM  ELSE @Status END		
	AND		A.ROW_STS_KEY	= 1) B
	
	ORDER BY CASE WHEN ISNULL(UPDT_DT,'') ='' THEN CREAT_DT ELSE UPDT_DT END  DESC
	
	
END
END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END



