


CREATE PROCEDURE [dbo].[Analyst_GetCVSSMetricScore]
(
	
	@CVSS_VER			VARCHAR(20),
	@MTRC_VCTR_CD		VARCHAR(3),
	@MTRC_VAL_VCTR_CD	VARCHAR(3)
	
)
AS
BEGIN


BEGIN TRY
SET NOCOUNT ON
		
		SELECT MTRC_GRP_NM,MTRC_NM,CVSS_VER,MTRC_VCTR_CD,MTRC_VAL_TXT,MTRC_VAL_VCTR_CD,MTRC_VAL_SCOR,VCTR_ORDR
	    FROM CVSS_SCOR_MTRC
		WHERE CVSS_VER = @CVSS_VER
		AND  MTRC_VCTR_CD = CASE WHEN @MTRC_VCTR_CD='' THEN MTRC_VCTR_CD ELSE @MTRC_VCTR_CD END
		AND  MTRC_VAL_VCTR_CD = CASE WHEN @MTRC_VAL_VCTR_CD='' THEN MTRC_VAL_VCTR_CD ELSE @MTRC_VAL_VCTR_CD END
		ORDER BY VCTR_ORDR
				  

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END



