CREATE PROCEDURE [dbo].[Analyst_GetComplianceInfoBycveID]
(
	
	@CVE_ID		 VARCHAR(25)
	
)
AS
BEGIN


BEGIN TRY
SET NOCOUNT ON
		
		SELECT  A.REG_CMPLN_CD, A.SECUR_CTL_FAM_CD,A.SECUR_CTL_FAM_NM,A.SECUR_OBJ_CD,A.SECUR_OBJ_NM,A.SECUR_CTL_NM,
				A.SECUR_CTL_DESC,A.SECUR_CTL_CD
		FROM	SECUR_CTL					A
		JOIN	CVE_SECUR_CTL_MAP			B	
		ON		A.SECUR_CTL_CD	        =	B.SECUR_CTL_CD	
		WHERE	B.CVE_ID				=   @CVE_ID
		AND		B.ROW_STS_KEY			=  1
			       


END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END
