CREATE PROCEDURE [dbo].[GetOrgSchmaLogByID]
(
	@ORG_KEY	INTEGER

)
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON

SELECT		TOP 1 ORG_KEY,CREAT_DT,CLNT_SCHM_LOG_KEY,ERR_DESC,SCHM_STS_DESC
FROM		CLNT_SCHM_LOG
WHERE		ORG_KEY = @ORG_KEY
ORDER BY	CLNT_SCHM_LOG_KEY DESC

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END
