CREATE PROCEDURE [dbo].[GetUserDetailsByName]
(
       @UserID  VARCHAR(150)
)
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON

SELECT A.USER_ID,A.ORG_KEY,A.USER_TYP_KEY,[dbo].[fnGetMasterLkpNameByID](A.USER_TYP_KEY) USER_TYPE,
	   A.ROW_STS_KEY,A.FST_NM,A.LST_NM,A.MIDL_NM,A.JOB_TITL_NM,A.EMAIL_ID,A.TEL_NBR,A.LCK_IND,
	   A.LOGIN_ATMPT_CNT,A.LST_LOGIN_DT,A.PSWD_RSET_DT,A.CREAT_DT,A.USER_VERF_IND,MAC_ADR_NM,
	   B.ROW_STS_KEY ORG_STS_KEY,B.ORG_NM,B.ORG_SCHM 
FROM   USER_PRFL	  A
JOIN    ORG           B
ON      A.ORG_KEY   = B.ORG_KEY 
WHERE  A.EMAIL_ID   = @UserID
END TRY

BEGIN CATCH


    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END;
