CREATE PROCEDURE [dbo].[INS_USER_SESS_LOG]
(
       @USER_ID      INTEGER,
       @EMAIL_ID     VARCHAR(150),
       @SESS_ID      VARCHAR(500),
       @LST_ACT_DT DATETIME
)
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON

INSERT USER_SESS_LOG(USER_ID,EMAIL_ID,SESS_ID,LST_ACT_DT) VALUES
(@USER_ID,@EMAIL_ID,@SESS_ID,@LST_ACT_DT)


SELECT SCOPE_IDENTITY() AS RETVAL
UPDATE  USER_PRFL
SET           LOGIN_ATMPT_CNT = 0
WHERE   USER_ID                   = @USER_ID
END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END;

