CREATE PROCEDURE [dbo].[INS_USER_EMAIL_LOG]
(
	@NTF_MSG_KEY		INTEGER,
	@USER_ID			INTEGER,
	@FROM_EMAIL_ID		VARCHAR(150),
	@TO_EMAIL_ID		TEXT,
	@CC_EMAIL_ID		TEXT,
	@BCC_EMAIL_ID		TEXT,
	@EMAIL_SND_DT		DATETIME,
	@EMAIL_MSG_SBJ_TXT	VARCHAR(255),
	@EMAIL_MSG_CNTN_TXT	TEXT,
	@SND_SUC_IND		INTEGER,
	@RESND_CNT			INTEGER,
	@ERR_DESC			VARCHAR(5000)
	
)
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON

INSERT USER_EMAIL_LOG(NTF_MSG_KEY ,USER_ID,FROM_EMAIL_ID,TO_EMAIL_ID,CC_EMAIL_ID,BCC_EMAIL_ID,EMAIL_SND_DT,EMAIL_MSG_SBJ_TXT,EMAIL_MSG_CNTN_TXT,SND_SUC_IND,RESND_CNT,ERR_DESC) VALUES
(@NTF_MSG_KEY,@USER_ID,@FROM_EMAIL_ID,@TO_EMAIL_ID,@CC_EMAIL_ID,@BCC_EMAIL_ID,@EMAIL_SND_DT,@EMAIL_MSG_SBJ_TXT,@EMAIL_MSG_CNTN_TXT,@SND_SUC_IND,@RESND_CNT,@ERR_DESC)


SELECT SCOPE_IDENTITY() AS RETVAL

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END;







