--DROP PROCEDURE LISTPERMSNGRP
CREATE PROCEDURE [dbo].[LIST_PermissionGroups]
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON

SELECT	A.PERMSN_GRP_KEY,A.ROW_STS_KEY,dbo.fnGetMasterLkpNameByID(A.ROW_STS_KEY) ROWSTATUS, A.PERMSN_GRP_NM,A.PERMSN_GRP_DESC,CONVERT(VARCHAR(10),A.UPDT_DT,101)UpdateDate,
		A.UPDT_USER_ID,dbo.fnGetUserNameByID(A.UPDT_USER_ID) USERNAME,CONVERT(VARCHAR(10),B.CREAT_DT,101)alterdDate,B.CREAT_USER_ID,A.STS_COMMT_TXT
FROM	PERMSN_GRP		  A
JOIN	USER_PRFL		  B
ON		A.CREAT_USER_ID = B.USER_ID
WHERE	A.ROW_STS_KEY	<> 3
ORDER BY CASE WHEN ISNULL(A.UPDT_DT,'')='' THEN A.CREAT_DT ELSE A.UPDT_DT END DESC 

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END;







