CREATE PROCEDURE [dbo].[LIST_ServicesByPkgkey]
(
	@SECUR_PKG_CD  VARCHAR(10)
)
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON

SELECT		DISTINCT B.SECUR_SRVC_CD,C.SECUR_SRVC_NM,C.SECUR_SRVC_DESC,A.SECUR_PKG_NM,A.SECUR_PKG_DESC--,D.SRVC_EST_STRT_DT,D.SRVC_EST_END_DT
FROM		SECUR_PKG					A
JOIN		SECUR_PKG_OFR				B
ON			A.SECUR_PKG_CD			=   B.SECUR_PKG_CD
AND			B.ROW_STS_KEY			=   1
JOIN		SECUR_SRVC					C
ON			B.SECUR_SRVC_CD			=   C.SECUR_SRVC_CD
AND			C.ROW_STS_KEY			=	1
--LEFT JOIN   CLNT_SECUR_SRVC_ENGMT   D
--ON			C.SECUR_SRVC_KEY		=  D.SECUR_SRVC_KEY
WHERE		A.SECUR_PKG_CD			=  @SECUR_PKG_CD


END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END






