CREATE PROCEDURE [dbo].[LIST_UserClntSrvcAssnTest]
(
	@USERTYPEID 	INTEGER,
	@CLNT_ENGMT_CD  VARCHAR(30),
	@USER_ID		INTEGER,
	@USER_TYP_KEY	INTEGER,
	@USERNAME		VARCHAR(300),
	@USER_STRT_DT	VARCHAR(10),
	@USER_END_DT	VARCHAR(10)


		
)
AS
BEGIN

DECLARE @LISERVICE VARCHAR(100) = ''
BEGIN TRY
SET NOCOUNT ON

IF @USERTYPEID = 16
BEGIN
SELECT		C.CLNT_ENGMT_CD,A.SECUR_SRVC_CD,A.SECUR_SRVC_NM,B.SRVC_EST_STRT_DT ,B.SRVC_EST_END_DT,
			[dbo].[fnGetMasterLkpNameByID](G.USER_TYP_KEY) UserType,D.ORG_TYP_KEY,D.ORG_NM,D.ORG_KEY,
			ISNULL(E.USER_CLNT_SRVC_ASGN_KEY,0)USER_CLNT_SRVC_ASGN_KEY,ISNULL(G.FST_NM+' '+G.LST_NM,'') USERNAME,
			ISNULL(E.USER_ID,0) USER_ID,ISNULL(E.ROW_STS_KEY,0) ROW_STS_KEY,
			E.USER_STRT_DT,E.USER_END_DT,G.USER_TYP_KEY
FROM		SECUR_SRVC				  A
JOIN		CLNT_SECUR_SRVC_ENGMT	  B
ON			A.SECUR_SRVC_CD			= B.SECUR_SRVC_CD
JOIN		CLNT_ENGMT				  C
ON			B.CLNT_ENGMT_CD			= C.CLNT_ENGMT_CD
JOIN		CLNT_ENGMT_USER_ASGN	  F
ON			C.CLNT_ENGMT_CD			= F.CLNT_ENGMT_CD
JOIN		USER_CLNT_SRVC_ASGN		  E
ON			C.CLNT_ENGMT_CD			= E.CLNT_ENGMT_CD
AND			B.SECUR_SRVC_CD			= E.SECUR_SRVC_CD
AND			CONVERT(VARCHAR(20),E.USER_STRT_DT,101)  = CASE WHEN @USER_STRT_DT = '' THEN CONVERT(VARCHAR(20),E.USER_STRT_DT,101) ELSE @USER_STRT_DT END
AND			CONVERT(VARCHAR(20),E.USER_END_DT,101)	 = CASE WHEN @USER_END_DT  = '' THEN CONVERT(VARCHAR(20),E.USER_END_DT,101)  ELSE @USER_END_DT END
LEFT JOIN		USER_PRFL				  G
ON			E.USER_ID				= G.USER_ID
AND			ISNULL(G.FST_NM+' '+G.LST_NM,'')  LIKE CASE WHEN ISNULL(@USERNAME,'') = '' THEN ISNULL(G.FST_NM+' '+G.LST_NM,'') ELSE '%@USERNAME%' END
JOIN		ORG						  D
ON			G.ORG_KEY				= D.ORG_KEY

AND         G.USER_TYP_KEY			= CASE WHEN @USER_TYP_KEY = 0 THEN G.USER_TYP_KEY ELSE @USER_TYP_KEY END

WHERE		C.CLNT_ENGMT_CD			= @CLNT_ENGMT_CD
AND			F.USER_ID				= @USER_ID

END


IF @USERTYPEID = 18
BEGIN

SELECT @LISERVICE = SECUR_SRVC_LIST_CD FROM dbo.CLNT_ENGMT_USER_ASGN A
JOIN dbo.USER_PRFL B ON A.USER_ID = B.USER_ID
WHERE CLNT_ENGMT_CD = @CLNT_ENGMT_CD AND B.USER_TYP_KEY= 18

SELECT		C.CLNT_ENGMT_CD,A.SECUR_SRVC_CD,A.SECUR_SRVC_NM,B.SRVC_EST_STRT_DT ,B.SRVC_EST_END_DT,
			[dbo].[fnGetMasterLkpNameByID](G.USER_TYP_KEY) UserType,D.ORG_TYP_KEY,D.ORG_NM,D.ORG_KEY,
			ISNULL(E.USER_CLNT_SRVC_ASGN_KEY,0)USER_CLNT_SRVC_ASGN_KEY,ISNULL(G.FST_NM+' '+G.LST_NM,'') USERNAME,
			ISNULL(E.USER_ID,0) USER_ID,ISNULL(E.ROW_STS_KEY,0) ROW_STS_KEY,
			E.USER_STRT_DT,E.USER_END_DT,G.USER_TYP_KEY
FROM		SECUR_SRVC				  A
JOIN		CLNT_SECUR_SRVC_ENGMT	  B
ON			A.SECUR_SRVC_CD			= B.SECUR_SRVC_CD
JOIN		CLNT_ENGMT				  C
ON			B.CLNT_ENGMT_CD			= C.CLNT_ENGMT_CD
JOIN		CLNT_ENGMT_USER_ASGN	  F
ON			C.CLNT_ENGMT_CD			= F.CLNT_ENGMT_CD
JOIN	    dbo.FnSplit(@LISERVICE,',')		  H
ON		    A.SECUR_SRVC_CD				=     H.items
LEFT JOIN		USER_CLNT_SRVC_ASGN		  E
ON			C.CLNT_ENGMT_CD			= E.CLNT_ENGMT_CD
AND			B.SECUR_SRVC_CD			= E.SECUR_SRVC_CD
LEFT JOIN		USER_PRFL				  G
ON			E.USER_ID				= G.USER_ID

JOIN		ORG						  D
ON			G.ORG_KEY				= D.ORG_KEY

AND			CONVERT(VARCHAR(20),E.USER_STRT_DT,101)  = CASE WHEN @USER_STRT_DT = '' THEN CONVERT(VARCHAR(20),E.USER_STRT_DT,101) ELSE @USER_STRT_DT END
AND			CONVERT(VARCHAR(20),E.USER_END_DT,101)	 = CASE WHEN @USER_END_DT  = '' THEN CONVERT(VARCHAR(20),E.USER_END_DT,101)  ELSE @USER_END_DT END
AND         G.USER_TYP_KEY			= CASE WHEN @USER_TYP_KEY = 0 THEN G.USER_TYP_KEY ELSE @USER_TYP_KEY END
AND			ISNULL((G.FST_NM+' '+G.LST_NM),'')  LIKE CASE WHEN ISNULL(@USERNAME,'') = '' THEN ISNULL(G.FST_NM+' '+G.LST_NM,'') ELSE '%' + @USERNAME + '%' END
WHERE		C.CLNT_ENGMT_CD			= @CLNT_ENGMT_CD
AND			F.USER_ID				= @USER_ID

END

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END








