
CREATE PROCEDURE [dbo].[REPORT_MatrixFindings]
(
       @CLNT_ENGMT_CD             VARCHAR(30),
	   @schema					  VARCHAR(50)  
  
)
AS
BEGIN

BEGIN TRY
SET NOCOUNT ON

DECLARE @Query VARCHAR(max)

	SET		 @Query ='
    SELECT   DISTINCT A.CLNT_VULN_INSTC_KEY ID,A.CLNT_ENGMT_CD,A.SECUR_SRVC_CD,A.VULN_NM, ISNULL(CONVERT(VARCHAR(MAX),A.VULN_DESC),'''')VULN_DESC,
		     ISNULL(CONVERT(VARCHAR(MAX), A.RECOM_COMMT_TXT),'''')RECOM,F.VULN_SEV_NM
    FROM     '+@schema+'.CLNT_VULN_INSTC		  A
	JOIN	 VULN_IMP				  B
	ON		 A.VULN_IMP_CD			= B.VULN_IMP_CD
	JOIN	 RMDTN_CST_EFFRT		  C
	ON		 A.RMDTN_CST_EFFRT_CD	= C.RMDTN_CST_EFFRT_CD
	JOIN	  VULN_SEV				  F
	ON		  A.VULN_SEV_CD		    = F.VULN_SEV_CD
	LEFT JOIN '+@schema+'.CLNT_VULN_SECUR_CTL	  D
	ON		 A.CLNT_VULN_INSTC_KEY	= D.CLNT_VULN_INSTC_KEY
	LEFT JOIN SECUR_CTL				  E
	ON		 D.REG_CMPLN_CD			= E.REG_CMPLN_CD
	AND		 D.SECUR_CTL_CD			= E.SECUR_CTL_CD
	AND		 D.REG_CMPLN_VER		= E.REG_CMPLN_VER
	AND		 E.REG_CMPLN_CD			= ''HITRUST''
	WHERE    CLNT_ENGMT_CD			= '''+@CLNT_ENGMT_CD+'''
	AND		 VULN_INSTC_STS_CD		NOT IN(''D'',''FP'')
	AND		 A.VULN_SEV_CD			NOT IN(''I'')
	AND		 B.VULN_IMP_CD			IN(''C'',''MJ'',''I'',''MI'',''IF'',''MO'') 
	AND		 C.RMDTN_CST_EFFRT_CD IN(''H'',''M'',''L'')
	AND		 A.ROW_STS_KEY		  = 1'
	EXECUTE (@Query)



END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END