CREATE PROCEDURE [dbo].[Report_TopOWASP]
(

	@CLNT_ENGMT_CD	VARCHAR(100),
	@SECUR_SRVC_CD	VARCHAR(100),
	@Flag			VARCHAR(2),-- AP - Application,SS-SSID,AL- ALL
	@APPNETCD		VARCHAR(500),
	@schema			VARCHAR(50)		
	
)
AS
BEGIN

BEGIN TRY
SET NOCOUNT ON
 DECLARE @Query VARCHAR(max)
 DECLARE @LiCOUNT INTEGER

	IF @Flag = 'AL'
	BEGIN
	SET		@Query ='	   
    SELECT   CLNT_ENGMT_CD,SECUR_SRVC_CD,B.OWASP_NM,COUNT(B.OWASP_TOP_10_KEY)OWASPCOUNT
    FROM     '+ @schema+'.CLNT_VULN_INSTC			  A
	JOIN	 OWASP_TOP_10				  B
	ON		 A.OWASP_TOP_10_KEY		=	  B.OWASP_TOP_10_KEY
	WHERE    CLNT_ENGMT_CD			=	  '''+@CLNT_ENGMT_CD + '''
	AND		 SECUR_SRVC_CD			=	  CASE WHEN '''+@SECUR_SRVC_CD+''' = '''' THEN SECUR_SRVC_CD ELSE '''+@SECUR_SRVC_CD +''' END
	AND		 VULN_INSTC_STS_CD		NOT IN(''D'',''FP'')
	AND		 VULN_SEV_CD			NOT IN(''I'')
	AND		 ROW_STS_KEY		= 1
    GROUP BY CLNT_ENGMT_CD,SECUR_SRVC_CD,B.OWASP_NM'
	EXECUTE (@Query)
	END

	IF @Flag = 'AP'
	BEGIN	   
	SET		@Query ='
	SELECT   CLNT_ENGMT_CD,SECUR_SRVC_CD,B.OWASP_NM,COUNT(B.OWASP_TOP_10_KEY)OWASPCOUNT
    FROM     '+ @schema+'.CLNT_VULN_INSTC			  A
	JOIN	 OWASP_TOP_10				  B
	ON		 A.OWASP_TOP_10_KEY		=	  B.OWASP_TOP_10_KEY
	JOIN	 dbo.FnSplit('''+@APPNETCD+''','','')   C
	ON		 A.SFTW_NM				=	  C.items
	WHERE    CLNT_ENGMT_CD			=	  '''+@CLNT_ENGMT_CD+'''
	AND		 SECUR_SRVC_CD			=	  CASE WHEN '''+ @SECUR_SRVC_CD + ''' = '''' THEN SECUR_SRVC_CD ELSE '''+ @SECUR_SRVC_CD+''' END
	AND		 VULN_INSTC_STS_CD		NOT IN(''D'',''FP'')
	AND		 VULN_SEV_CD			NOT IN(''I'')
	AND		 ROW_STS_KEY			= 1
    GROUP BY CLNT_ENGMT_CD,SECUR_SRVC_CD,B.OWASP_NM'
	EXECUTE (@Query)
	END

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END
