CREATE PROCEDURE [dbo].[Reports_INSReportFileUploadLog](
	@ROW_STS_KEY          INTEGER,
	@ORG_KEY              INTEGER,
	@CLNT_ENGMT_CD        VARCHAR(30),
	@RPT_NM_KEY           INTEGER,
	@RPT_STS_KEY		  INTEGER,  
	@FL_NM				  VARCHAR(150),
	@FL_FLDR_PTH		  VARCHAR(500),
	@USER_ID			  INTEGER,
	@FL_SZ				  VARCHAR(100)
	

	)
	AS
	BEGIN
		BEGIN TRY

		SET NOCOUNT ON


			INSERT RPT_FL_UPLOAD_LOG(ROW_STS_KEY,ORG_KEY,CLNT_ENGMT_CD,RPT_NM_KEY,RPT_STS_KEY,FL_NM,FL_FLDR_PTH,CREAT_USER_ID,CREAT_DT,FL_SZ ) VALUES
			(@ROW_STS_KEY,@ORG_KEY,@CLNT_ENGMT_CD,@RPT_NM_KEY,@RPT_STS_KEY,@FL_NM,@FL_FLDR_PTH,@USER_ID,GETDATE(),@FL_SZ)

			SELECT SCOPE_IDENTITY() AS RETVAL

		END TRY

		BEGIN CATCH
			

			DECLARE @ErrorNumber INT = ERROR_NUMBER();
			DECLARE @ErrorLine INT = ERROR_LINE();
			DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
			DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
			DECLARE @ErrorState INT = ERROR_STATE();

			PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
			PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

			RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
		  END CATCH
		
	END;