CREATE PROCEDURE  [dbo].[Report_FindingDetails]
(
	@CLNT_ENGMT_CD		 VARCHAR(100),
	@SECUR_SRVC_CD		 VARCHAR(100),
	@VULN_SEV_CD		 VARCHAR(50),
	@VULN_CATGY_CD		 VARCHAR(500),
	@SchemaName			 VARCHAR(50)
)
AS
BEGIN

BEGIN TRY
SET NOCOUNT ON
DECLARE @Query VARCHAR(MAX)

SET @Query='
 SELECT	  CLNT_VULN_INSTC_KEY ID,CLNT_ENGMT_CD,SECUR_SRVC_CD,VULN_SEV_NM,VULN_NM,VULN_DESC,RECOM_COMMT_TXT,
		  VULN_TECH_COMMT_TXT,HITRUST,FedRAMP,NIST,CSACCM,FISMA,MARSE,SOC2,PCIDSS,HIPAA,ISO,IRS,VULN_CATGY_NM,
		  VULN_CATGY_CD 
 FROM	  '+ @SchemaName+ '.Findings
 WHERE    CLNT_ENGMT_CD						= '''+@CLNT_ENGMT_CD+'''
 AND	  VULN_INSTC_STS_CD					NOT IN(''D'',''FP'')
 AND	  VULN_SEV_CD						NOT IN(''I'')
 AND	  1= CASE WHEN '''+@SECUR_SRVC_CD+'''		= '''' THEN 1	WHEN SECUR_SRVC_CD IN (SELECT Items FROM Dbo.FnSplit('''+@SECUR_SRVC_CD+''','','')) THEN 1 END
 AND	  1= CASE WHEN '''+@VULN_SEV_CD+'''			= ''''   THEN 1	WHEN VULN_SEV_CD IN (SELECT Items FROM Dbo.FnSplit('''+@VULN_SEV_CD+''','',''))		THEN 1 END
 AND	  1= CASE WHEN '''+@VULN_CATGY_CD+'''  = ''''  THEN 1	WHEN LTRIM(RTRIM(VULN_CATGY_CD)) IN (SELECT Items FROM Dbo.FnSplit(LTRIM(RTRIM('''+@VULN_CATGY_CD+''')),'',''))	THEN 1 END
 AND	  VULN_INSTC_STS_CD  NOT IN(''D'',''FP'')
 AND	  VULN_SEV_CD		NOT IN(''I'')
'
-- PRINT (@Query)
EXECUTE(@Query)
END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END




