CREATE PROCEDURE [dbo].[Report_GetRemediationFindingListByEngmtcd]
(
       
	   @CLNT_ENGMT_CD		 VARCHAR(30)
	   			

)
AS
BEGIN

BEGIN TRY
SET NOCOUNT ON

		SELECT	A.CLNT_VULN_INSTC_KEY,A.CLNT_ENGMT_CD,A.VULN_NM,A.SECUR_SRVC_CD,B.SECUR_SRVC_NM,A.VULN_SRC_KEY,
				C.LKP_ENTY_NM,A.VULN_SEV_CD,D.VULN_SEV_NM,E.VULN_INSTC_STS_NM,A.UPDT_DT,A.CREAT_DT
		FROM	CLNT_VULN_INSTC			A
		JOIN	SECUR_SRVC				B
		ON		B.SECUR_SRVC_CD		=   A.SECUR_SRVC_CD
		JOIN	MSTR_LKP				C
		ON		A.VULN_SRC_KEY		=   C.MSTR_LKP_KEY
		JOIN	VULN_INSTC_STS			E
		ON		E.VULN_INSTC_STS_CD	=   A.VULN_INSTC_STS_CD
		LEFT JOIN	VULN_SEV				D
		ON		D.VULN_SEV_CD		=   A.VULN_SEV_CD	

		
		WHERE	A.CLNT_ENGMT_CD		=	@CLNT_ENGMT_CD
		AND		A.VULN_INSTC_STS_CD IN ('C','V')
		AND		A.ROW_STS_KEY		= 1
		ORDER BY CASE WHEN ISNULL(A.UPDT_DT,'') ='' THEN A.CREAT_DT ELSE A.UPDT_DT END DESC
	   

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END

