CREATE PROCEDURE [dbo].[UPDATE_UserSecurDtlByID]
(
	@USER_SECUR_DTL_KEY	INTEGER,
	@ROW_STS_KEY		INTEGER,
	@USER_ID			INTEGER,
	@SECUR_QUES_KEY		INTEGER,
	@ANS_TXT			VARCHAR(1000),
	@SEQ_ORDR_NBR		INTEGER,
	@UPDT_USER_ID		INTEGER
				  

)
AS
BEGIN
BEGIN TRY
SET NOCOUNT ON


BEGIN 
      UPDATE dbo.USER_SECUR_DTL 
      SET    ROW_STS_KEY		 =   @ROW_STS_KEY,
			 SECUR_QUES_KEY		 =   @SECUR_QUES_KEY,
			 ANS_TXT	         =   @ANS_TXT,
			 SEQ_ORDR_NBR	     =   @SEQ_ORDR_NBR,
			 UPDT_DT			 =	 GETDATE(),
	         UPDT_USER_ID		 =   @UPDT_USER_ID
      WHERE  USER_SECUR_DTL_KEY	 =   @USER_SECUR_DTL_KEY
      AND	 USER_ID			 =   @USER_ID
      
	  SELECT @@ROWCOUNT AS RETVAL
END 

END TRY

BEGIN CATCH

    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    PRINT 'Actual error number: ' + CAST(@ErrorNumber AS VARCHAR(10));
    PRINT 'Actual line number: ' + CAST(@ErrorLine AS VARCHAR(10));

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
-- COMMIT TRANSACTION
END







